<?php /* Template Name: LadogubetsPublications */

?>

<?php
/**
 * @package start_theme
 * 
 */

get_header(); ?>
<html>

<head>

</head>

<body>


    <div class="wrapper">
        <div class="bannerScience">
            <div class="column">
                <div class="text-banner">
                    <p><br></p>
                    <p><b>Не знаєш де опублікувати свою роботу?</b></p>
                    <p>Слідкуй за рубрикою <a href="#">Конференції</a>. Завжди корисна інформація, ключові дати та активні контакти!</p>
                    <p><br></p>
                </div>
            </div>
        </div>
        <div class="text-page">
            <h1>Публікації: Ладогубець В.В.</h1>
            <br>

            <ol>
                <li>Інформаційні системи прийняття рішень і логічних висновків : Методичні вказівки до виконання комплексної контрольної роботи для студентів напряму підготовки 6.050101 «Комп’ютерні науки», спеціальності 8.05010103 «Системне проектування» денної та заочної форм навчання / Укладачі : О.Ю. Безносик, В.В. Ладогубець, О.Д. Фіногенов. – К. : НТУУ «КПІ», 2013 р. – 33 c.</li>
                <li>Теорія прийняття рішень : Методичні вказівки до виконання лабораторних робіт для студентів напряму підготовки 6.050101 «Комп’ютерні науки», спеціальностей 8.05010102 «Інформаційні технології проектування» та 8.05010103 «Системне проектування» денної та заочної форм навчання / Укладачі : О.Ю. Безносик, В.В. Ладогубець, О.Д. Фіногенов. – К. : НТУУ «КПІ», 2013 р. – 76 c.</li>
                <li>Ladogubets V. Employing Engines for Engineering Calculations / Volodymyr Ladogubets, Bogdan Bulakh, Vitalii Chekaliuk, Oleksandr Kramar // The Experience of Designing and Application of CAD Systems in Microelectronics : 12-th Intern. Conf. «CADSM’2013», 19-23 February 2013, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv, 2013. – P. 427–430. – ISBN 978-617-607-393-2.</li>
                <li>Petrenko A. Simulation in GridALLTED Complex / Anatolii Petrenko, Mykhailo Lobur, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh, Tetyana Ladogubets // The Experience of Designing and Application of CAD Systems in Microelectronics : 12-th Intern. Conf. «CADSM’2013», 19-23 February 2013, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv, 2013. – P. 422–424. – ISBN 978-617-607-393-2.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_016.pdf" mce_href="/attachments/043_2013_016.pdf">Zgurovsky M. WebALLTED: Interdisciplinary Modeling in Grid and Cloud / Zgurovsky Michael, Anatolii Petrenko, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh // Computer Science. – Krakow : AGH, 2013. – № 14 (2). – P. 295–306.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_036.pdf" mce_href="/attachments/043_2012_036.pdf">Згуровскьий М.З. Математичне моделювання як грід-сервіс / Згуровський М.З., Петренко А.І., Ладогубець В.В. // Праці міжнародної конференції "Кластерні обчислення", 12-14 червня 2012 р., Київ, Україна. - К. : Інститут кібернетики імені В.М. Глушкова НАН України, 2012.&nbsp;- С. 24-28.</a></li>
                <li>Теорія прийняття рішень : Методичні вказівки до виконання комплексної контрольної роботи для студентів спеціальностей 8.05010102 «Інформаційні технології проектування» та 8.05010103 «Системне проектування» денної та заочної форм навчання / Укладачі : О.Ю. Безносик, В.В. Ладогубець, О.Д. Фіногенов. – К. : НТУУ «КПІ», 2012 р. – 42 c.</li>
                <li>Згуровський М.З. Математичне моделювання в сервісно-орієнтованому грід-середовищі / Згуровський М.З., Петренко А.І., Ладогубець В.В. // «Моделирование-2012», 16-18 мая 2012, Киев : сб. тр. конф. – Киев, 2012. – С. 191–194.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_043.pdf" mce_href="/attachments/043_2012_043.pdf">Кирюша Б.А. Подходы к устранению конфликтов при совместном аналогово-цифровом моделировании / Кирюша Б.А., Ладогубец В.В. // Інформатика, управління та обчислювальна техніка : вісник НТУУ «КПІ». – 2012. – Вип. 55. – С. 181–186.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_050.pdf" mce_href="/attachments/043_2012_050.pdf">Булах Б.В. Модификация способа учета баланса загрузки при выполнении параллельных программ на вычислительном кластере / Булах Б.В., Чекалюк В.В., Ладогубец В.В., Финогенов А.Д. // Інформатика, управління та обчислювальна техніка : вісник НТУУ «КПІ». – 2012. – Вип. 57. – С. 56–59.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_040.pdf" mce_href="/attachments/043_2012_040.pdf">Zgurovsky M. WebALLTED: Interdisciplinary Simulator Based on Grid Services / Zgurovsky M., Petrenko A., Ladogubets V., Finogenov O., Bulakh B. // East-West Design &amp; Test Symposium : 10-th IEEE East-West Design &amp; Test Symposium «EWDTS’2012», 14-17 September 2012, Kharkov, Ukraine: proc. – Kharkov, 2012. – P. 126–129.</a></li>
                <li>Методи багатокритеріальної та мінімаксної оптимізації : Методичні вказівки до виконання лабораторних робіт для студентів спеціальностей 8.05010102 «Інформаційні технології проектування» та 8.05010103 «Системне проектування» денної та заочної форм навчання / Укладачі : В.В. Ладогубець, О.Д. Фіногенов. – К. : НТУУ «КПІ», 2012 р. – 109 c.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_013.pdf" mce_href="/attachments/043_2012_013.pdf">Ладогубець В.В. Графічний редактор схем управління / Ладогубець В.В., Ляпін П.С., Мельничук Р.М. // Системный анализ и информационные технологии: 14-я международная научно-техническая конференция «САИТ-2012», 24 апреля 2012, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2012. – С. 289.</a></li>
                <li>Petrenko A. Service-Oriented Architecture for Grid-Enabled Computer Simulation Software / Anatolii Petrenko, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh // Perspective Technologies and Methods in MEMS Design : 8-th International Conference MEMSTECH’2012, 18-21 April 2012, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2012. – P. 179–181.</li>
                <li>Ladogubets V. An Approach to the Size Reduction for Very Large Circuit Equivalents of MEMS Non-Electrical Parts Mathematical Model / Volodymyr Ladogubets, Oleksii Finogenov, Oleksandr Beznosyk, Oleksandr Popov, Michal Szermer, Wojciech Zabierowski, Piotr Zajac // Perspective Technologies and Methods in MEMS Design : 8-th International Conference MEMSTECH’2012, 18-21 April 2012, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2012. – P. 174–177.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_003.pdf" mce_href="/attachments/043_2012_003.pdf">Ladogubets V.V. Forming a User Function Dynamic Library for ALLTED CAD Software / Ladogubets V.V., Finogenov O.D., Beznosyk O. Yu. // Electronics and Nanotechnology : 32-th International Scientific Conference «ELNANO’2012», 10-12 April 2012, Kiev, Ukraine : proc. – Kiev, 2012. – P. &nbsp;123.</a></li>
                <li>Ладогубец В.В. Объединение пакета NetALLTED со сторонними пакетами САПР / Ладогубец В.В., Финогенов А.Д., Старовойтенко Д.С. // Комп’ютерні технології: наука і освіта : 4-а Всеукраїнська науково-практична конференція : тези доповідей. ­– К. : Університиет «Україна», 2012. – С. 59–62.</li>
                <li>Zgurovsky M. WebALLTED: Interdisciplinary Simulation in Grid / Michael Zgurovsky, Anatoly Petrenko, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh // Cracow Grid Workshop : 12-th Cracow Grid Workshop «CGW’12», 22-24 October 2012, Krakow, Poland : proc. – Krakow, 2012. – P. 61–62. – ISBN 978-83-61433-06-4.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_047.pdf" mce_href="/attachments/043_2011_047.pdf">Корначевський Я.І. Генетичні алгоритми в САПР / Корначевський Я.І., Ладогубець В.В. // Інформатика, управління та обчислювальна техніка : вісник НТУУ «КПІ». – 2011. – Вип. 54. – С. 48–53.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_045.pdf" mce_href="/attachments/043_2011_045.pdf">Методичні вказівки до виконання лабораторних робіт з дисципліни «Методи оптимізації» для студентів напряму підготовки 6.050101 «Комп'ютерні науки», спеціальностей 8.05010102 «Інформаційні технології проектування» та&nbsp; 8.05010103 «Системне проектування» денної та заочної форм навчання / Укл. В.В.Бобін, В.В.Ладогубець, О.Д.Фіногенов. – Львів : ПП «Вежа і Ко», 2011 р. – 128 c. – ISBN 978-617-607-230-0.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_043.pdf" mce_href="/attachments/043_2011_043.pdf">Ладогубець В.В. Матричний алгоритм скорочення розмірності схемотехнічних моделей МЕМС / Ладогубець В.В., Безносик О.Ю., Кот Д.М. // Вісник університету «Україна» : Інформатика, обчислювальна техніка та кібернетика. – К. : Університет «Україна», 2011. – № 2. – С. 268–272.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_035.pdf" mce_href="/attachments/043_2011_035.pdf">Петренко А.І. Дослідження архітектури комплексу схемотехнічного моделювання GridALLTED / Петренко А.І., Ладогубець В.В., Фіногенов О.Д., Булах Б.В. // Вісник університету «Україна» : Інформатика, обчислювальна техніка та кібернетика. – К. : Університет «Україна», 2011. – № 2. – С. 65–70.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_034.pdf" mce_href="/attachments/043_2011_034.pdf">Ладогубец В.В. Методы выбора размера шага для параллельного алгоритма динамического анализа / Ладогубец В.В., Крамар. А.В., Финогенов А.Д. // Вісник університету «Україна» : Інформатика, обчислювальна техніка та кібернетика. – К. : Університет «Україна», 2011. – № 2. – С. 12–17.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_029.pdf" mce_href="/attachments/043_2011_029.pdf">Ладогубец В.В. Анализ методов управления вычислениями при моделировании сложных объектов // Ладогубец В.В., Финогенов А.Д., Безносик А.Ю. // Математические методы в технике и технологиях : 24-я международная конференция «ММТТ-24» : 2011, Саратов, Россия : сб. тр. в 10-ти томах. – К. : Национальный техн. ун-т. Украины «КПИ», 2011. – Т. 1. – С. 142–144.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_027.pdf" mce_href="/attachments/043_2011_027.pdf">Ладогубец В.В. Портал моделирования WebAllted / Ладогубец В.В., Скрипка М.Ю. // Системный анализ и информационные технологии : 13-я международная научно-техническая конференция «САИТ-2011», 23-28 мая 2011, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2011. – С. 457.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_018.pdf" mce_href="/attachments/043_2011_018.pdf">Ладогубець В.В. Модифікації алгоритму Санжованні-Вінсентеллі / Ладогубець В.В., Кот Д.М., Попов О.О. // Системный анализ и информационные технологии : 13-я международная научно-техническая конференция «САИТ-2011», 23-28 мая 2011, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2011. – С. 379.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_007.pdf" mce_href="/attachments/043_2011_007.pdf">Ladogubets V. Choosing an Objective Function Type When Adjusting Mechanical Components’ Macromodel Parameters / Oleksandr Beznosyk, Oleksii Finogenov, Volodymyr Ladogubets // Perspective Technologies and Methods in MEMS Design : 7-th International Conference MEMSTECH’2011, 11-14 May 2011, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2011. – P. 239–240.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_006.pdf" mce_href="/attachments/043_2011_006.pdf">Napieralski A. Actual Tasks and Trends in Developing Multidomain MEMS Models for Educational Purposes / Andzej Napieralski, Michal Szermer, Mykhaylo Lobur, Oleh Matviykiv, Anatolii Petrenko, Volodymyr Ladogubets // Perspective Technologies and Methods in MEMS Design : 7-th International Conference MEMSTECH’2011, 11-14 May 2011, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2011. – P. 237–238.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_003.pdf" mce_href="/attachments/043_2011_003.pdf">Ладогубець В.В. Методи підвищення ефективності Y–Δ перетворення при побудові схемних макромоделей МЕМС / Ладогубець В.В., Фіногенов О.Д., Безносик О.Ю. // Электроника и связь : тематический выпуск «Электроника и нанотехнологии». – 2011. – № 1. – С. 82–87.</a><span> </span><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_003abs.pdf" mce_href="/attachments/043_2011_003abs.pdf">Тези</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_002.pdf" mce_href="/attachments/043_2011_002.pdf">Ladogubets V. Features of the Optimization of Mechanical Component Macromodels / Vladimir Ladogubets, Oleksii Finogenov, Oleksandr Beznosyk, Tatiana Ladogubets // The Experience of Designing and Application of CAD Systems in Microelectronics : 11-th Anniversary Intern. Conf. «CADSM’2011», 23-25 February 2011, Lviv-Polyana (Zakarpattya), Ukraine : proc. – Lviv, 2011. – P. 410–412.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_056.pdf" mce_href="/attachments/043_2010_056.pdf">Ладогубець В.В. Особливості оптимізації макромоделей механічних компонентів / Ладогубець В.В., Фіногенов О.Д., Безносик О.Ю. // Інформатика, управління та обчислювальна техніка : вісник НТУУ «КПІ». – 2010. – Вип. 52. – С. 96–102.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_051.pdf" mce_href="/attachments/043_2010_051.pdf">Ладогубець В.В. Підвищення надійності методів керування обчисленнями / Ладогубець В.В., Крамар О.В., Фіногенов О.Д. // Інформатика, обчислювальна техніка та кібернетика : Вісник Університету «Україна». – К. : Університет «Україна», 2010. – №8. – С. 96–100.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_043.pdf" mce_href="/attachments/043_2010_043.pdf">Ладогубец В.В. Методы выбора размера шага для параллельного алгоритма динамического анализа / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Комп’ютерні технології: наука і освіта : 5-а Всеукраїнська науково-практична конференція : тези доп. – Київ, 2010. – С. 134–138.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_038.pdf" mce_href="/attachments/043_2010_038.pdf">Ladogubets V. Straight Pipeline Simulation / Ladogubets V., Tchkalov O., Beznosyk O., Finogenov O. // CAD in Machinery Design. Implementation and Educational Problems : 18-th Ukranian–Polish Conference «CADMD’2010», October 14-16, 2010, Lviv, Ukraine: Proc. – Lviv: Vezha &amp; Co , 2010. – P. 23–26.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_020.pdf" mce_href="/attachments/043_2010_020.pdf">Ладогубец В.В. Уменьшение обменов данными для параллельного алгоритма СПУИП / Ладогубец В.В., Куц П.О., Фишман Д.Э. // Системный анализ и информационные технологии : 12-я международная научно-техническая конференция "САИТ-2010", 25-29 мая 2010, Киев, Украина : материалы. - К. : УНК "ИПСА" НТУУ "КПИ", 2010. - С. 374.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_019.pdf" mce_href="/attachments/043_2010_019.pdf">Ладогубец В.В. Методы управления динамическим анализом сложных объектов / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Системный анализ и информационные технологии : 12-я международная научно-техническая конференция "САИТ-2010", 25-29 мая 2010, Киев, Украина : материалы. - К. : УНК "ИПСА" НТУУ "КПИ", 2010. - С. 373.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_001.pdf" mce_href="/attachments/043_2010_001.pdf">Oleksandr Beznosyk. Presentation of a System of Ordinary Differential Equations as an Equivalent Electrical Circuit / Oleksandr Beznosyk, Oleksii Finogenov, Volodymyr Ladogubets // Perspective Technologies and Methods in MEMS Design : VI-th International Conference MEMSTECH’2010, 20-23 April 2010, Lviv-Polyana, Ukraine: proc. – Lviv : Publishing House Vezha &amp; Co , 2010. – P. 116–120.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_003.pdf" mce_href="/attachments/043_2010_003.pdf">Ладогубец В.В. Использование мультипроцессорных вычислительных систем средствами схемотехнического проектирования / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Электроника и связь : тематический выпуск «Электроника и нанотехнологии». – 2010. – № 5. – С. 232–235.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_005.pdf" mce_href="/attachments/043_2009_005.pdf">Anatolii Petrenko. Using Optimization Procedures to Calculate Parameters of MEMS Macromodels / Anatolii Petrenko, Volodymyr Ladogubets, Oleksandr Beznosyk, Oleksii Finogenov // The Experience of Designing and Application of CAD Systems in Microelectronics : 10-th Anniversary Intern. Conf. «CADSM’2009», 24-28 February 2009, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv, 2009. – P. 511–514.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_006.pdf" mce_href="/attachments/043_2009_006.pdf">Oleksandr Beznosyk. Making a Mechanical Components Library for Circuit Design Software / Oleksandr Beznosyk, Oleksii Finogenov, Volodymyr Ladogubets, Oleksii Tchkalov // Perspective Technologies and Methods in MEMS Design : V-th International Conference MEMSTECH’2009, 22-24 April 2009, Lviv-Polyana, Ukraine: proc. – Lviv : Publishing House Vezha &amp; Co , 2009. – P. 120–122.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_008.pdf" mce_href="/attachments/043_2009_008.pdf">Безносик А.Ю. Использование пакетов схемотехнического проектирования для расчета деформаций механических компонентов / Безносик А.Ю., Ладогубец В.В., Финогенов А.Д.,&nbsp; Чкалов А.В. // Системный анализ и информационные технологии : 11-я международная научно-техническая конференция «САИТ-2009», 26-30 мая 2009, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2009. – С. 419.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_013.pdf" mce_href="/attachments/043_2009_013.pdf">Ладогубец В.В. Анализ эффективности выбора порядка в неявном методе численного интегрирования на основе разностей высших порядков / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Системный анализ и информационные технологии : 11-я международная научно-техническая конференция «САИТ-2009», 26-30 мая 2009, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2009. – С. 436.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_020.pdf" mce_href="/attachments/043_2009_020.pdf">Петренко А.І. Використання пакетів схемотехнічного проектування для побудови моделей механічних компонентів / Петренко А.І., Ладогубець В.В., Фіногенов О.Д. [та ін.] // Вісник НУ «Львівська політехніка»: Комп’ютерні науки та інформаційні технології. – 2009. – № 638. – С. 18-22.</a></li>
                <li>Петренко А.И. Расчет собственных частот мембранных структур с использованием пакетов схемотехнического проектирования / Петренко А.И., Ладогубец В.В., Финогенов А.Д. [и др.] // Радиоэлектроника. – 2009. – № 7. – С. 19–25. – (Известия вузов).</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_032.pdf" mce_href="/attachments/043_2009_032.pdf">Ладогубец В.В. Расчет времени выполнения параллельного метода численного интегрирования на основе разностей высших порядков / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Вісник НТУУ «КПІ». Інформатика, управління та обчислювальна техніка: Зб. наук. пр. – К. : ВЕК+, 2009. – № 50. – С. 23–29.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_002.pdf" mce_href="/attachments/043_2009_002.pdf">Ладогубец В.В. Методика построения моделей механических компонентов МЭМС для пакетов схемотехнического проектирования / Ладогубец В.В., Чкалов А.В., Безносик А.Ю., Финогенов А.Д. // Электроника и связь : тематический выпуск «Электроника и нанотехнологии». – 2009. – Ч. 1, № 2/3. – С. 298–305.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_025.pdf" mce_href="/attachments/043_2008_025.pdf">Ладогубец В.В. Метод построения макромоделей МЭМС / Ладогубец В.В., Чкалов&nbsp;А.В., Безносик А.Ю.,&nbsp; Финогенов А.Д. // СВЧ-техника и телекоммуникационные технологии : 18-я Международная Крымская конференция «КрыМиКо’2008», 8-12 сент. 2008, Севастополь, Крым, Украина : материалы. – Севастополь: Вебер, 2008. – Т. 1. – С. 147–148.</a></li>
                <li>Ладогубец В.В. Метод формирования схемных реализаций математических моделей неэлектрических объектов / Ладогубец В.В., Чкалов&nbsp;А.В., Безносик А.Ю.,&nbsp; Финогенов А.Д. // Моделювання та інформаційні технології : зб. наук. пр. – 2008. – Вип. 46. – С.&nbsp;114–120.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_012.pdf" mce_href="/attachments/043_2008_012.pdf">Безносик О.Ю.&nbsp;Використання пакетів схемотехнічного проектування для моделювання механічних компонентів / Безносик О.Ю., Ладогубець В.В., Фіногенов О.Д., Чкалов&nbsp;О.В. // Системний аналіз та інформаційні технології : 10-а міжнародна науково-технічна конференція «САІТ-2008», 20-24 травня 2008, Київ, Україна : матеріали. – К. : НТУУ «КПІ», 2008. – С. 286.</a></li>
                <li>Ладогубец В.В. Адаптация параллельного алгоритма СПУИП для кластера НТУУ «КПИ» / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Вісник НТУУ «КПІ». Інформатика, управління та обчислювальна техніка: Зб. наук. пр. – 2008. – № 48. – С. 99–103.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_011.pdf" mce_href="/attachments/043_2008_011.pdf">Безносик А.Ю. Построение пассивных моделей МЭМС / Безносик А.Ю., Ладогубец В.В., Финогенов А.Д., Чкалов&nbsp;А.В. // Системный анализ и информационные технологии : 10-я международная научно-техническая конференция «САИТ-2008», 20-24 мая 2008, Киев, Украина : материалы. – К.: НТУУ «КПИ», 2008. – С. 285.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_001.pdf" mce_href="/attachments/043_2008_001.pdf">Ладогубец В.В. Методы макромоделирования МЭМС / Ладогубец В.В., Безносик А.Ю., Крамар А.В., Финогенов А.Д. // Электроника и связь : тематический выпуск «Проблемы электроники». – 2008. – Ч. 1. – С. 244–248.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_023.pdf" mce_href="/attachments/043_2008_023.pdf">Beznosyk O. Using circuit design software to simulate microelectromechanical components / Beznosyk O., Finogenov O., Ladogubets V., Tchkalov O. // Perspective Technologies and Methods in MEMS Design : IV-th International Conference of Young Scientists MEMSTECH’2008, 21-24 May 2008, Lviv-Polyana, Ukraine: proc. – Lviv : Publishing House Vezha &amp; Co , 2008. – P. 130–133.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2007_009.pdf" mce_href="/attachments/043_2007_009.pdf">Ладогубец В.В. Параллельный алгоритм численного интегрирования, основывающийся на разностях высших порядков с варьируемым шагом и порядком метода / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Системный анализ и информационные технологии : 9-я международная научно-техническая конференция «САИТ-2007», Киев : материалы.. – К.: НТУУ «КПИ», 2007. – С. 156.</a></li>
                <li>Ладогубец В.В. Параллельный алгоритм численного интегрирования математических моделей сложных систем&nbsp;/ Ладогубец В.В., Финогенов А.Д. // Электроника и связь : тематический выпуск «Проблемы электроники». – 2007. – Ч. 1. – С. 101–104.</li>
                <li>Ладогубец В.В. Параллельные алгоритмы вычислительной математики (курс лекций) / Ладогубец В.В. – К. : «Аверс», 2006. – 84 с.</li>
                <li>Ладогубець В.В. Алгоритми параметричної оптимізації складних систем (курс лекцій) / Ладогубець В.В., Ладогубець Т.С., Ладогубець О.В. – К. : «Аверс», 2006. – 139 с.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2005_010.pdf" mce_href="/attachments/043_2005_010.pdf">Ладогубец В.В. Пути повышения эффективности программных средств САПР / Ладогубец В.В., Финогенов А.Д.// СВЧ-техника и телекоммуникационные технологии : 15-я Международная Крымская конференция «КрыМиКо’2005», 12-16 сент. 2005, Севастополь, Крым, Украина : материалы. – Севастополь: Вебер, 2005. – Т. 2. – С. 472–473.</a></li>
                <li>Петренко А.І. Архітектура мереженого комплексу схемотехнічного проектування ALLTED / Петренко А.І., Ладогубець В.В., Воєвода О.О. // Комп’ютерні системи проектування. Теорія і практика : вісник НУ «Львівська політехніка». – 2005. – № 522. – С. 30–33.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2005_005.pdf" mce_href="/attachments/043_2005_005.pdf">Ладогубец В.В. Состояние и перспективы развития автоматизированного схемотехнического проектирования / Ладогубец В.В. // Электроника и связь : тематический выпуск «Проблемы электроники». – 2005. – Ч. 1. – С. 121–127.</a></li>
                <li>Финогенов А.Д. Особенности реализации параллельных алгоритмов для однопроцессорных пакетов / Финогенов А.Д., Ладогубец В.В. // Электроника и связь. – 2005. – № 25. – С. 95–98.</li>
                <li>Ладогубець В.В. Особливості реалізації мереженої взаємодії в комплексі схемотехнічного проектування ALLTED / Ладогубець В.В., Воєвода О.О. // Комп’ютерні системи проектування. Теорія і практика : вісник НУ «Львівська політехніка». – 2004. – № 501. – С. 27–31.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2004_007.pdf" mce_href="/attachments/043_2004_007.pdf">В.В. Ладогубец. Тестовые задачи параметрической оптимизации схем на МОП транзисторах / В.В. Ладогубец, А.В. Ладогубец / Электроника и связь. – 2004. – № 22. – С. 49–53.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2004_003.pdf" mce_href="/attachments/043_2004_003.pdf">Корначевський Я.І. Порівняльне дослідження модифікацій моделей BSIM 3v3, вбудованих в пакети схемотехнічного проектування ALLTED та SPICE / Корначевський Я.І., Ладогубець В.В. // Электроника и связь. – 2004. – № 21. – С. 30–33.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2004_004.pdf" mce_href="/attachments/043_2004_004.pdf">Ю.А. Руденко. Алгоритм уменьшения размерности RLC цепей / Ю.А. Руденко, В.В.Ладогубец , А.В. Ладогубец // Электроника и связь. – 2004. – № 21. – С. 72–74.</a></li>
                <li>Ладогубец В.В. Эффективный алгоритм решения общей задачи нелинейного программирования при схемотехническом проектировании / Ладогубец В.В., Ладогубец А.В. // Электроника и связь. – 2003. – № 19. – С. 3–6.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2003_002.pdf" mce_href="/attachments/043_2003_002.pdf">Ладогубец В.В. Особенности EKV модели КМОП транзисторов / Ладогубец В.В., Руденко Ю.А. // Электроника и связь. – 2003. – № 18. – С. 11–13.</a></li>
                <li>Ладогубець В.В. Аналіз можливостей використання паралельних обчислень для формування математичних моделей складних об’єктів / Ладогубець В.В., Сорокін Ю.В., Калюжний О.О. // Электроника и связь. – 2003. – № 18. – С. 80–82.</li>
                <li>Петренко А.І. Принципи побудови мереженого комплексу схемотехнічного проектування ALLTED / Петренко А.І., Ладогубець В.В., Воєвода О.О. // Электроника и связь. – 2002. – № 17. – С. 56–58.</li>
                <li>Капшук О.А. Микросенсоры потоков и их проектирование / Капшук О.А., Рабышко В.А., Ладогубец В.В., Крамар А.В. // Электроника и связь. – 2002. – № 17. – С. 108–112.</li>
                <li>Корначевський Я.І. Особливості реалізації інверсного режиму в КМОН моделях на прикладі BSIM / Корначевський Я.І., Ладогубець В.В. // Электроника и связь. – 2002. – № 17. – С. 3–7.</li>
                <li>Ладогубець В.В. Організація off-line взаємодії з пакетом схемотехнічного моделювання ALLTED / Ладогубець В.В., Воєвода О.О. // Электроника и связь. – 2002. – № 16. – С. 39–41.</li>
                <li>Петренко А.И. Формирование графического представления соединений схемы замещения в схемных редакторах / Петренко А.И., Ладогубец В.В., Марченко Е.В. // Электроника и связь. – 2000. – № 9. – С. 18–31.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2000_012.pdf" mce_href="/attachments/043_2000_012.pdf">Ладогубец В.В. Алгоритм определения задержек в переключательных МОП-цепях / Ладогубец В.В. // Радиоэлектроника. – 2000. – № 2. – С. 72–79. – (Известия вузов).</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1999_015.pdf" mce_href="/attachments/043_1999_015.pdf">Ладогубец В.В. Средства параллельных вычислений в САПР / Ладогубец В.В., Харченко К.В. // Радиоэлектроника. – 1999. – № 2. – С. 51–60. – (Известия вузов).</a></li>
                <li>Петренко А.И. Подсистема графического ввода САПР ALLTED / Петренко А.И., Ладогубец В.В., Марченко Е.В. // Электроника и связь. – 1999. – № 7. – С. 107–109.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1999_002.pdf" mce_href="/attachments/043_1999_002.pdf">Ладогубець В.В. Алгоритм оптимального балансу загрузки / Ладогубець В.В. // Электроника и связь. – 1999. – Т. 1, № 6. – С. 74–76.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_010.pdf" mce_href="/attachments/043_1998_010.pdf">Ладогубец В.В. Подход к определению задержек в переключательных МОП-цепях / Ладогубец В.В. // Электроника и связь. – 1998. – Ч. 2. – № 4. – С. 261–265.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_009.pdf" mce_href="/attachments/043_1998_009.pdf">Ладогубец В.В. Применение параллельных вычислений в схемотехническом моделировании / Ладогубец В.В., Харченко К.В. // Электроника и связь. – 1998. – Ч. 2.– № 4. – С. 231–234.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_008.pdf" mce_href="/attachments/043_1998_008.pdf">Нгуен Х.Ч. Концепция релаксации и временной анализ интегрированных МОП-цепей / Нгуен Х.Ч., Ладогубец В.В., Петренко А.И. // Радиоэлектроника. – 1998. – № 8. – С. 60–67. – (Известия вузов).</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_007.pdf" mce_href="/attachments/043_1998_007.pdf">Нгуен Х.Ч. Алгоритм временного моделирования при экспресс-анализе цепей на МОП-транзисторах / Нгуен Х.Ч., Ладогубец В.В., Петренко А.И. // Радиоэлектроника. – 1998. – № 3. – С. 40–48. – (Известия вузов).</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1997_005.pdf" mce_href="/attachments/043_1997_005.pdf">Ладогубец В.В. Организация параллельных вычислений в САПР / Ладогубец В.В., Харченко К.В. //Электроника и связь. – 1997. – Ч. 2. – № 3. – С. 48-50.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1997_001.pdf" mce_href="/attachments/043_1997_001.pdf">Нгуен Х.Ч. Экспериментальная программа реализации метода волновой релаксации при экспресс-анализе МОП-схем / Нгуен Х.Ч., Ладогубец В.В. //Электроника и связь. – 1997. – Ч. 1. – № 2. – С. 28-32.</a></li>
            </ol>

        </div>
    </div>

    <?php get_footer(); ?>
</body>

</html>