<?php /* Template Name: PetrenkoPublications */

?>

<?php
/**
 * @package start_theme
 * 
 */

get_header(); ?>
<html>

<head>

</head>

<body>


    <div class="wrapper">
        <div class="bannerScience">
            <div class="column">
                <div class="text-banner">
                    <p><br></p>
                    <p><b>Не знаєш де опублікувати свою роботу?</b></p>
                    <p>Слідкуй за рубрикою <a href="#">Конференції</a>. Завжди корисна інформація, ключові дати та активні контакти!</p>
                    <p><br></p>
                </div>
            </div>
        </div>
        <div class="text-page">
            <h1>Публікації: Петренко Анатолій Іванович</h1>
            <br>

            <ol>
                <li><a href="/attachments/043_2017_01_p.pdf" mce_href="/attachments/043_2017_01_p.pdf" target="_blank">Petrenko A.I. Services and a Distributed Ecosystem for Supporting Mobile Medical Application Development // J Telecommun Syst Manage 5: 140, 2016. doi: 10.4172/2167-0919.1000140</a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_02_p.pdf" mce_href="/attachments/043_2017_02_p.pdf" target="_blank">O.O. Petrenko. A loosely-integrated suite of services for mhealth formed by wireless sensor networks / O.O. Petrenko, A.I. Petrenko -// Data Stream Mining &amp; Processing. Proc. of the 1 th IEEE International Conference on Data Stream Mining &amp; Processing, 23-27 August 2016, Lviv, Ukraine, pp.3-8.</a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_03_p.pdf" mce_href="/attachments/043_2017_03_p.pdf" target="_blank">Petrenko A.I. Personal healthcare platform for chronic diseases with mobile self-management support / Petrenko A.I. Roenko N.V.- // The 4-th International Virtual Conference on Advanced Scientific Results, Slovakia, 6-10 June, 2016, www.scieconf.com</a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_04_p.pdf" mce_href="/attachments/043_2017_04_p.pdf" target="_blank">Petrenko A.I. Cloud based Simulation Platform for Circuits and Systems Design / Petrenko A.I. , Petrenko I.A.- // III International Scientific and Practical Conference "Innovative Technologies in Science" (February 28, 2017, Dubai, UAE).</a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_05_p.pdf" mce_href="/attachments/043_2017_05_p.pdf" target="_blank">Петренко А.А. Семантическое модельно-управляемое моделирование архитектуры системы сервисов / Петренко А.А., Петренко А.И. - //Электронное моделирование, №5, 2016</a><br mce_bogus="1"></li>
                <!--     <li>Петренко А.А. Семантическое модельно-управляемое моделирование архитектуры системы сервисов /Петренко А.А., Петренко А.И. // Электронное моделирование. - №2, 2016.</li> -->
                <li><a href="/attachments/043_2017_06_p.pdf" mce_href="/attachments/043_2017_06_p.pdf" target="_blank">Petrenko A.I. Virtual Research Environment “Optimal Engineering Design as a Service Ecosystem” -// Proceedings of the International Scientific and Practical Conference«Modern Science Problems (May 18, 2016, Kiev, Ukraine)», http://webofscholar.com/docs/3.pdf</a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_07_p.pdf" mce_href="/attachments/043_2017_07_p.pdf" target="_blank">Петренко А.И. Процессно-ориентированное проектирование программных комплексов как систем сервисов -// System Research &amp; Information Technologies, 2016, № 4, рр.46-56
                    </a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_08_p.pdf" mce_href="/attachments/043_2017_08_p.pdf" target="_blank">V. Giedrimas. Distributed software development tools for distributed scientific applications / V. Giedrimas, L. Sakalauskas, A. Petrenko -// Book “"Parallel and Distributed Computing", ISBN 978-953-51-5255-2, Chapter 2. InTech, 2017.</a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_09_p.pdf" mce_href="/attachments/043_2017_09_p.pdf" target="_blank">O. Shadura. Multivariate analysis: genetic algorithm and uncentered PCA / O. Shadura, A. Petrenko, S. Svistunov -// System Research &amp; Information Technologies, 2017, № 1.</a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_10_p.pdf" mce_href="/attachments/043_2017_10_p.pdf" target="_blank">Petrenko A.I. Collaborative Complex Computing environment (Com-Com) // Journal of Computer Science &amp; Systems Biology, CA 94404, USA, Biol 8, August 2015, pp. 278-284.</a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_11_p.pdf" mce_href="/attachments/043_2017_11_p.pdf" target="_blank">Петренко І.А., Петренко А. Автоматизовані методи пошуку і відкриття необхідних сервісів / Петренко І.А., Петренко А.І. -// Вісник Університету «Україна», Серія «Інформатика, обчислювальна техніка та кібернетика» №1(17), грудень 2015, стр. 55-64.</a><br mce_bogus="1"></li>
                <li><a href="/attachments/043_2017_00_bul_serviceorchestration.pdf" mce_href="/attachments/043_2017_00_bul_serviceorchestration.pdf" target="_blank">А.І.Петренко, Б.В.Булах. Прикладне програмування як оркестрування сервісів. Навчальний посібник. ННК ІПСА. 2016 р. - 150 с.</a><br mce_bogus="1"></li>
                <li>Кисельов Г.Д. Наука про сервіси, менеджмент та інжиніринг як основа інноваційної діяльності /Кисельов Г.Д., Петренко О.О.// Вісник Університету «Україна», Серія «Інформатика, обчислювальна техніка та кібернетика», №2(18), 2015, стр.28-36.</li>
                <li>Петренко І.А. Автоматизовані методи пошуку і відкриття необхідних сервісів/ Петренко І.А., Петренко О.О. // Вісник Університету «Україна», Серія «Інформатика, обчислювальна техніка та кібернетика», №1(17), 2015, С. 55-64</li>

                <li>Петренко O.O. Моделювання архітектури системи сервісів /Петренко O.O., Петренко А.І. // Праці міжнародної науково-технічної конференції «Моделювання-2016», м. Київ (Україна), травень 2016</li>
                <li>Petrenko I.A., Petrenko A.I. Optimization and simulation of complex non-linear systems and circuits as the composition of cloud services.-// Journal "International Scientific and Practical Conference "WORLD SCIENCE" ("Modern Scientific Achievements and Their Practical Application"), 2015</li>
                <!--     <li>Petrenko A.I. A loosely-integrated suite of services for mhealth formed by wireless sensor networks/ Petrenko A.A., Petrenko A.I.-// The 1-th IEEE International Conference on Data Stream Mining & Processing, 23-27 August 2016, Lviv, Ukraine</li> -->
                <li>Petrenko A.I. Virtual Research Environment “Optimal Engineering Design as a Service Ecosystem” -// Proceedings of the International Scientific and Practical Conference «Modern Science Problems (May 18, 2016, Kiev, Ukraine)»</li>
                <!--     <li>Petrenko A.I.   Collaborative Complex Computing environment (Com-Com).-//  Journal of Computer Science & Systems Biology, CA 94404, USA. Biol 8, 2015, pp.278-284</li> -->
                <!--     <li>Petrenko I.A., Petrenko A.I.   Optimization and simulation of complex non-linear systems and circuits as the composition of cloud services.-// Journal "International Scientific and Practical Conference "WORLD SCIENCE" ("Modern Scientific Achievements and Their Practical Application"), 2015.</li> -->
                <li>Петренко А.І. Цифровая наука в программе Горизонт-2020.-// Cистемні дослідження і інформаційні технології, №1, 2015</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2015_00_p.pdf" mce_href="http://cad.kpi.ua/attachments/043_2015_00_p.pdf">Петренко А.І. Сервісно-орієнтоване дослідницьке середовище з складних обчислень.-// Proc. of 17-th International conference on System Analysis and Information Technologies SAIT 2015,</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_09_p.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_09_p.pdf">Anatoly I. Petrenko. EnvironmentService-Oriented Computing in a Cloud Computing.-// Proc. of Computer Science and Applications Volume 1, Number 6, 2014, pp. 349-358</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2014_01_p.pdf" mce_href="http://cad.kpi.ua/attachments/043_2014_01_p.pdf">Petrenko A.I. Mobile health applications to support the diabetic patient and the doctor.-// Proc. of East-West Design and Test Conference (EWDT-14), Kiev, 27-29 Sept.2014.</a><br mce_bogus="1"></li>
                <li>Петренко А.І. Мобiльна платформа взаємодiїлiкарiв та хронiчних хворих пацiєнтiв (платформа "Mobimed").-// 14-я международная научно-техническая конференция «САИТ-2014», Киев, Україна, травень 2014.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2014_03_p.pdf" mce_href="http://cad.kpi.ua/attachments/043_2014_03_p.pdf">Згуровский М.З., Петренко А.И. Становление и горизонты цифровой науки.-// Системні дослідження і інформаційні технології.-Київ, №4, 2014.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2014_00_p.pdf" mce_href="http://cad.kpi.ua/attachments/043_2014_00_p.pdf">Petrenko A.I. Virtual Research Environment “Optimal Engineering Design as a Service”.-// Proc. EGI Community Forum 2014 – Helsinki, May 2014/</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_10_p.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_10_p.pdf">Petrenko A.I. Service-oriented computing (SOC) in a cloud computing environment.-// Proc. of East-West Design and Test Conference (EWDT-13), Rostov-on-Don, 15-18 Sept.2013.</a><br mce_bogus="1"></li>
                <li>Svirin P. Advanced Brokers for Nordugrid ARC Using Web-Services. / A. Petrenko, S. Svistunov, P. Svirin // Східно-Європейський журнал передових технологій, №3/9 (63), 2013 – с. 60-63.</li>
                <li>Петренко А.І. Моделювання складних систем. К. : НТУУ «КПІ», 2013 р. – 216 c.; гриф факультету (інституту); № протоколу Ради 3; дата отримання грифу 21.11.2013. Цей конспект лекцій у видавництві розглядався як монографія.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_016.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_016.pdf">Zgurovsky M. WebALLTED: Interdisciplinary Modeling in Grid and Cloud / Zgurovsky Michael, Anatolii Petrenko, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh // Computer Science. – Krakow : AGH, 2013. – № 14 (2). – P. 295–306.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_024.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_024.pdf">Petrenko A.I. Service-oriented Computing (SOC) in Engineering Practice / Petrenko A.I. // Cracow Grid Workshop : 13-th Cracow Grid Workshop «CGW’13», 4-6 November 2013, Krakow, Poland : proc. – Krakow : AGH, 2013. – P. 73–74.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_005.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_005.pdf">Петренко А.І. Хмарні обчислення в комп’ютеризації проектування / Петренко А.І. // Системный анализ и информационные технологии : 15-я международная научно-техническая конференция "САИТ-2013", 27-31 мая 2013, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2013. – С. 24–25.</a><br mce_bogus="1"></li>
                <li>Petrenko A. Distributed Grid Brokers Architecture Using Web-Services / Petrenko A., Svistunov S., Svirin P. // Cluster Computing : Second International Conference «CC’2013», 3-5 June 2013, Lviv, Ukraine : proc. – Lviv, 2013. – P. 175–178.</li>
                <li>Петренко А.И. Новые подходы для брокера ресурсов Nordugrid ARC / Петренко А.И., Свистунов С.Я., Свирин П.В. // СВЧ-техника и телекоммуникационные технологии : 23-я Международная Крымская конференция «КрыМиКо’2013», 9-13 сент. 2013, Севастополь, Крым, Украина : материалы. – Севастополь, 2013. – С. 352–353.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_019.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_019.pdf">Petrenko A. Advanced brokers for Nordugrid ARC using web-services / Petrenko A., Svistunov S., Svirin P. // Восточно-Европейский журнал передовых технологий. – 2013. – № 3/9 (63). – С. 60–63.</a><br mce_bogus="1"></li>
                <li>Petrenko A.I. Service-oriented computing (SOC) in Engineering Design.-// Proc. of Third International Conference on High Performance Computing (HPC-UA-2013), Kiev, October 2013.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_018.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_018.pdf">Петренко А.І. Гібридний алгоритм брокера для NorduGridARC 2.0 для використання в сегменті УНГ / А.І. Петренко, С.Я. Свістунов, П.В. Свірін // Восточно-Европейский журнал передовых технологий. – 2013. – № 1/2 (61). – С. 4–6.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_025.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_025.pdf">Tkanko O.V. Using ontology for querying in relational database / Tkanko O.V., Petrenko A.I. // Системні дослідження та інформаційні технології. – 2013. – № 3. – С. 45–52.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_011.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_011.pdf">Бритов О.А. Виявлення точок інтересу методом інтегральних проекцій / Бритов О.А., Петренко А.І. // Системный анализ и информационные технологии : 15-я международная научно-техническая конференция "САИТ-2013", 27-31 мая 2013, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2013. – С. 402–403.</a><br mce_bogus="1"></li>
                <li>Petrenko A.I. Service-oriented computing (SOC) in Engineering Practice.-// Proc. of- the Thirteenth Cracow Grid Workshop (CGW'13), Krakow, Poland, November 4 - 6, 2013.</li>
                <li>Petrenko A. Simulation in GridALLTED Complex / Anatolii Petrenko, Mykhailo Lobur, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh, Tetyana Ladogubets // The Experience of Designing and Application of CAD Systems in Microelectronics : 12-th Intern. Conf. «CADSM’2013», 19-23 February 2013, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv, 2013. – P. 422–424. – ISBN 978-617-607-393-2.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_020.pdf" mce_href="http://cad.kpi.ua/attachments/043_2013_020.pdf">Петренко А.І. Брокер ресурсів для Nordugrid ARC із використанням прогнозування часу початку виконання. / Петренко А.І., Свистунов С.Я., Свірін П.В. // Моделювання та інформаційні технології : зб. наук. пр. – 2013. – Вип. 68. – С. 170–176.</a><br mce_bogus="1"></li>
                <li>Згуровський М.З. Математичне моделювання в сервісно-орієнтованому грід-середовищі / Згуровський М.З., Петренко А.І., Ладогубець В.В. // «Моделирование-2012», 16-18 мая 2012, Киев : сб. тр. конф. – Киев, 2012. – С. 191–194.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_042.pdf" mce_href="http://cad.kpi.ua/attachments/043_2012_042.pdf">Петренко А.І. Автоматизація виконання потоків робіт у Грід із залученнім грід-сервісів / Петренко А.І., Булах Б.В., Чекалюк В.В. // Інформатика, управління та обчислювальна техніка : вісник НТУУ «КПІ». – 2012. – Вип. 55. – С. 70–76.</a><br mce_bogus="1"></li>
                <li>Zgurovsky M. WebALLTED: Interdisciplinary Simulation in Grid / Michael Zgurovsky, Anatoly Petrenko, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh // Cracow Grid Workshop : 12-th Cracow Grid Workshop «CGW’12», 22-24 October 2012, Krakow, Poland : proc. – Krakow, 2012. – P. 61–62. – ISBN 978-83-61433-06-4.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_040.pdf" mce_href="http://cad.kpi.ua/attachments/043_2012_040.pdf">Zgurovsky M. WebALLTED: Interdisciplinary Simulator Based on Grid Services / Zgurovsky M., Petrenko A., Ladogubets V., Finogenov O., Bulakh B. // East-West Design &amp; Test Symposium : 10-th IEEE East-West Design &amp; Test Symposium «EWDTS’2012», 14-17 September 2012, Kharkov, Ukraine: proc. – Kharkov, 2012. – P. 126–129.</a><br mce_bogus="1"></li>
                <li>Петренко А.І. Система керування потоками обчислень на основі стандарту WS-BPEL для розв’язання інженерних задач / Петренко А.І., Булах Б.В. // Вісник НУ «Львівська політехніка»: Комп’ютерні науки та інформаційні технології. – 2012. – № 732. – С. 96-106.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_038.pdf" mce_href="http://cad.kpi.ua/attachments/043_2012_038.pdf">Згуровський М.З. Тенденції розвитку ІТ технологій / Згуровський М.З., Петренко А.І. // Праці міжнародної конференції "Кластерні обчислення", 12-14 червня 2012 р., Київ, Україна. - К. : Інститут кібернетики імені В.М. Глушкова НАН України, 2012. - С. 67-70.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_037.pdf" mce_href="http://cad.kpi.ua/attachments/043_2012_037.pdf">Петренко А.І. Хмарні і грід-обчислення для Е-Науки / Петренко А.І. // Праці міжнародної конференції "Кластерні обчислення", 12-14 червня 2012 р., Київ, Україна. - К. : Інститут кібернетики імені В.М. Глушкова НАН України, 2012. - С. 36-39.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_036.pdf" mce_href="http://cad.kpi.ua/attachments/043_2012_036.pdf">Згуровскьий М.З. Математичне моделювання як грід-сервіс / Згуровський М.З., Петренко А.І., Ладогубець В.В. // Праці міжнародної конференції "Кластерні обчислення", 12-14 червня 2012 р., Київ, Україна. - К. : Інститут кібернетики імені В.М. Глушкова НАН України, 2012. - С. 24-28.</a><br mce_bogus="1"></li>
                <li>Petrenko A.I. Microelectromechanical Systems and Devices : monograph / Petrenko A.I. – InTech, 2012. – Chapter 8. – P. 155–191. – ISBN: 978-953-51-0306-6. – Режим доступу : http://www.intechopen.com/books/microelectromechanical-systems-and-devices/macromodels-of-micro-electro-</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_053.pdf" mce_href="http://cad.kpi.ua/attachments/043_2012_053.pdf">Згуровський М.З. Оброблення наукових даниз в умовах інформаційного «буму» / Згуровський М.З., Петренко А.І. // Системні дослідження та інформаційні технології. – 2012. – № 2. – С. 7–25.</a><br mce_bogus="1"></li>
                <li>Петренко, А. Гібридний алгоритм брокера для Nordugrid ARC 2.0 / А. Петренко, С. Свістунов, П. Свірін // Високопродуктивні обчислення : міжнародна конференція «HPC-UA’2012», 8-10 жовтня 2012, Киев, Украина : матеріали. – К. : НТУУ «КПІ», 2012. – С. 275–277.</li>
                <li>На шляху до європейського грід : довід. (проект) для магістрів напряму підготов. «Комп’ютерні науки» / За ред. А.Г. Загороднього, М.З. Згуровського. – К. : НТУУ «КПІ», 2012. – 392 с. – ISBN 978-966-622-549-1.</li>
                <li>Petrenko A. Service-Oriented Architecture for Grid-Enabled Computer Simulation Software / Anatolii Petrenko, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh // Perspective Technologies and Methods in MEMS Design : 8-th International Conference MEMSTECH’2012, 18-21 April 2012, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2012. – P. 179–181.</li>
                <li>Свірін П.В. Стратегії балансування навантаження в грід / Петренко А.І., Свірін П.В., Свистунов С.Я. // Комп’ютерні технології: наука і освіта : 4-а Всеукраїнська науково-практична конференція : тези доповідей. ¬– К. : Університиет «Україна», 2012. – С. 52–56.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_016.pdf" mce_href="http://cad.kpi.ua/attachments/043_2012_016.pdf">Петренко А.І. Хмарні і Грід обчислення для е-науки / Петренко А.І. // Системный анализ и информационные технологии: 14-я международная научно-техническая конференция «САИТ-2012», 24 апреля 2012, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2012. – С. 294–295.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_021.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_021.pdf">Петренко А.І. Алгоритм оцінки завантаженості ГРІД-сайту / Свірін П.В., Петренко А.І., Свістунов С.Я. // Системный анализ и информационные технологии : 13-я международная научно-техническая конференция «САИТ-2011», 23-28 мая 2011, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2011. – С. 388.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_030.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_030.pdf">Петренко А.І. Концепція нової магістерської програми «Системне проектування» / Петренко А.І. // Обчислювальний інтеллект : 1-а міжнародна науково-технічна конференція «ОІ-2011», 10-13 травня 2011, Черкаси, Україна : матеріали. – Черкаси : Маклаут, 2011. – С. 39–41.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_038.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_038.pdf">Булах Б.В. BPEL-орієнтована система управління інженерними та науковими обчислювальними сценаріями / Булах Б.В., Петренко А.І. // Вісник університету «Україна» : Інформатика, обчислювальна техніка та кібернетика. – К. : Університет «Україна», 2011. – № 2. – С. 90–100.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_008.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_008.pdf">Петренко А.І. Грід-системи з розробки та оптимізації інженерних рішень / Петренко А.І. // Системный анализ и информационные технологии : 13-я международная научно-техническая конференция «САИТ-2011», 23-28 мая 2011, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2011. – С. 36–37.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_006.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_006.pdf">Napieralski A. Actual Tasks and Trends in Developing Multidomain MEMS Models for Educational Purposes / Andzej Napieralski, Michal Szermer, Mykhaylo Lobur, Oleh Matviykiv, Anatolii Petrenko, Volodymyr Ladogubets // Perspective Technologies and Methods in MEMS Design : 7-th International Conference MEMSTECH’2011, 11-14 May 2011, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2011. – P. 237–238.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_005.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_005.pdf">Petrenko A. Design Methodology and Workflow for MEMS Design / Petrenko Anatoliy // Perspective Technologies and Methods in MEMS Design : 7-th International Conference MEMSTECH’2011, 11-14 May 2011, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2011. – P. 12–15.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_001.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_001.pdf">Petrenko A. Macromodels of Micro-Electro – Mechanical Systems (MEMS) / Anatolii Petrenko A.I.. // The Experience of Designing and Application of CAD Systems in Microelectronics : 11-th Anniversary Intern. Conf. «CADSM’2011», 23-25 February 2011, Lviv-Polyana (Zakarpattya), Ukraine : proc. – Lviv, 2011. – P. 373–379.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_046.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_046.pdf">Петренко А.І. Застосування workflow-систем для потреб сучасних науки та інженерії / Петренко А.І., Булах Б.В. // Наукові вісті НТУУ "КПІ". — 2011. — № 5. — С. 40–51.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_048.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_048.pdf">Петренко А.И. Алгоритмы балансирования нагрузки в Грид-системах / Петренко А.И., Свистунов С.Я., Свирин П.В. // Системні дослідження та інформаційні технології. – 2011. – № 4. – С. 21–36.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_035.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_035.pdf">Петренко А.І. Дослідження архітектури комплексу схемотехнічного моделювання GridALLTED / Петренко А.І., Ладогубець В.В., Фіногенов О.Д., Булах Б.В. // Вісник університету «Україна» : Інформатика, обчислювальна техніка та кібернетика. – К. : Університет «Україна», 2011. – № 2. – С. 65–70.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_033.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_033.pdf">Петренко А.І. Практикум з грід-технологій : навчальний посібник / Петренко А.І., Свістунов С.Я., Кисельов Г.Д. – К. : НТУУ «КПІ», 2011. – 580 с.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_032.pdf" mce_href="http://cad.kpi.ua/attachments/043_2011_032.pdf">Згуровський М.З. На шляху до екзабайтного інформаційного середовища / Згуровський М.З., Петренко А.І. // Високопродуктивні обчислення : міжнародна конференція «HPC-UA’2011», 12-14 жовтня 2011, Київ : матеріали. – 2011. – К. : Політехніка, 2011. – С. 84–87.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_007.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_007.pdf">Петренко А.І. Комп’ютерне моделювання грід-систем / Петренко А.І. // Электроника и связь : тематический выпуск «Электроника и нанотехнологии». – 2010. – № 5. – С. 40–48.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_049.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_049.pdf">Петренко А.І. Методологія розробки онтологій / Петренко А.І. // Інформатика, обчислювальна техніка та кібернетика : Вісник Університету «Україна». – К. : Університет «Україна», 2010. – №8. – С. 56–71.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_023.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_023.pdf">Петренко А.І. Інструментарій розробки онтологій / Петренко А.І., Хондар В.С. // Системний аналіз та інформаційні технології : 12-а міжнародна науково-технична конференція "САІТ-2010", 25-29 травня 2010, Київ, Україна : материали. - К. : ННК "ІПСА" НТУУ "КПІ", 2010. - С. 380. </a><span>&nbsp; </span><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_023ppt.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_023ppt.pdf">Тези</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_047.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_047.pdf">Петренко А.І. Семантичний Грід для науки і освіти : роздатковий матеріал до вивч. курсу / Петренко А.І., Булах В.В., Хондар В.С. – К. : НТУУ «КПІ», 2010. – 180 с.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_044.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_044.pdf">Петренко А.І. Семантичний Грід для інтелектуального оброблення даних / Петренко А.І. // Комп’ютерні технології: наука і освіта : 5-а Всеукраїнська науково-практична конференція : тези доп. – Київ, 2010. – С. 169–172.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_036.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_036.pdf">Петренко А.І. Е-наука на шляху до семантичного Грід. Частина 2: Семантичний Web– і семантичний Грід / Згуровський М.З., Петренко А.І. // Системні дослідження та інформаційні технології. – 2010. – № 2. – С. 7–25.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_032.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_032.pdf">Петренко А.І. Е-наука на шляху до семантичного Грід. Частина 1: об’єднання Web– і Грід–технологій / Згуровський М.З., Петренко А.І. // Системні дослідження та інформаційні технології. – 2010. – № 1. – С. 27–38.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_055.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_055.pdf">Петренко А.І. Програмний інструментарій для моделювання Грід-систем / Петренко А.І., Шинкарюк Д.Ю. // Системні науки та кібернетика. – 2010. – № 1. – С. 123–129.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_005.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_005.pdf">Петренко А.І. Паралельний алгоритм скорочення розмірності RLC-схем / Петренко А.І., Попов О.О., Кот Д.М. // Электроника и связь : тематический выпуск «Электроника и нанотехнологии». – 2010. – № 4. – С. 40–44.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_022.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_022.pdf">Петренко А.І. Комп'ютерні хмарні обчислення в Грід технологіях / Петренко А.І., Оленович Є.В. // Системний аналіз та інформаційні технології : 12-а міжнародна науково-технична конференція "САІТ-2010", 25-29 травня 2010, Київ, Україна : материали. - К. : ННК "ІПСА" НТУУ "КПІ", 2010. - С. 379.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_010.pdf" mce_href="http://cad.kpi.ua/attachments/043_2010_010.pdf">Петренко А.І. Моделювання грід-систем / Петренко А.І. // Системний аналіз та інформаційні технології : 12-а міжнародна науково-технична конференція "САІТ-2010", 25-29 травня 2010, Київ, Україна : материали. - К. : ННК "ІПСА" НТУУ "КПІ", 2010. - С. 31-33.</a><br mce_bogus="1"></li>
                <li>Петренко А.І. Моделювання грід-систем і в грід-системах / Петренко А.І. // Моделювання та інформаційні технології : Зб. наук.пр. : спец. випуск «Матеріали міжнародної наукової конференції «Моделювання-2010», 12-14 травня 2010 р.». – 2010. – Т. 1. – С. 11–21.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_004.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_004.pdf">Zgurovsky M. Integrating Ukraine into European Grid Infrastructure / Zagorodny A., Zgurovsky M., Petrenko A. [et al.] // Системні дослідження та інформаційні технології. – 2009. – № 2. – С. 35–49.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_042.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_042.pdf">Петренко А.І. Чисельні методи. Лабораторний практикум / Фельдман Л.П., Петренко А.І., Дмитрієва О.А. – Донецьк : ДонНТУ, 2009. – 320 с.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_033.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_033.pdf">Петренко А.И. Программа моделирования процесса экспонирования речиста в электронно-лучевой литографии / Петренко А.И., Молявко А.С. // Вісник НТУУ «КПІ». Інформатика, управління та обчислювальна техніка: Зб. наук. пр. – К. : ВЕК+, 2009. – № 50. – С. 30–33.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_023.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_023.pdf">Згуровський М.З. Створення національної Grid-інфраструктури для забезпечення наукових досліджень / Згуровський М.З., Петренко А.І., Кисельов Г.Д. // Інформаційні технології в освіті. – 2009. – № 4. – С. 12–17.</a><br mce_bogus="1"></li>
                <li>Petrenko A.I. Networked VLSI and MEMS Designer for Grid / Petrenko A.I. // East-West Design and Test : сonference (EWDT-09), 18-21 Sept.2009, Moscow, Russia : proc. – Moscow, 2009. – P. 432–436.</li>
                <li>Петренко А.І. Програмне Grid забезпечення платформи gLite / Петренко А.І. // Наукові вісті університету «Україна». – 2009. – № 3.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_014.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_014.pdf">Петренко А.И. Создание Grid-портала национальной Grid-инфраструктуры на базе экспериментального Grid-портала SDGrid / Петренко А.И., Киселев Г.Д., Хондарь В.С. // Системный анализ и информационные технологии : 11-я международная научно-техническая конференция «САИТ-2009», 26-30 мая 2009, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2009. – С. 440.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_007.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_007.pdf">Петренко А.І. Семантичний Грід для гнучкого оброблення даних / Петренко А.І. // Системний аналіз та інформаційні технології : 11-а міжнародна науково-технічна конф. «САІТ–2009», 26-30 травня 2009 р., Київ : матеріали конф. – К. : НТУУ «КПІ», 2009. – С. 35–36.</a><br mce_bogus="1"></li>
                <li>Петренко А.І. Застосування Grid-технологій в науці і освіті / Петренко А.І. – К. : Політехніка, 2009. – 144 с.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_019.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_019.pdf">Петренко А.І. Моделювання експозиції резисту в електронно-променевій літографії / Петренко А.І., Молявко О.С. // Прикладна математика та комп'ютинг : 1-а наукова конференція магістратів та аспірантів «ПМК-2009», 15-17 квітня 2009, Київ, Україна : зб. тез / ред. кол. : С.В. Сирота (гол. ред.) та ін. – К. : НТУУ "КПІ", 2009. – С. 240–243.</a><br mce_bogus="1"></li>
                <li>Петренко А.И. Расчет собственных частот мембранных структур с использованием пакетов схемотехнического проектирования / Петренко А.И., Ладогубец В.В., Финогенов А.Д. [и др.] // Радиоэлектроника. – 2009. – № 7. – С. 19–25. – (Известия вузов).</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_005.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_005.pdf">Anatolii Petrenko. Using Optimization Procedures to Calculate Parameters of MEMS Macromodels / Anatolii Petrenko, Volodymyr Ladogubets, Oleksandr Beznosyk, Oleksii Finogenov // The Experience of Designing and Application of CAD Systems in Microelectronics : 10-th Anniversary Intern. Conf. «CADSM’2009», 24-28 February 2009, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv, 2009. – P. 511–514.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_020.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_020.pdf">Петренко А.І. Використання пакетів схемотехнічного проектування для побудови моделей механічних компонентів / Петренко А.І., Ладогубець В.В., Фіногенов О.Д. [та ін.] // Вісник НУ «Львівська політехніка»: Комп’ютерні науки та інформаційні технології. – 2009. – № 638. – С. 18-22.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_024.pdf" mce_href="http://cad.kpi.ua/attachments/043_2009_024.pdf">Згуровський М.З. Grid – технології для е-науки і освіти / Згуровський М.З., Петренко А.І. // Наукові вісті НТУУ «КПІ». – 2009. – № 2. – С. 10–17.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_004.pdf" mce_href="http://cad.kpi.ua/attachments/043_2008_004.pdf">А.І. Петренко. Grid та інтелектуальна обробка даних Data Mining / А.І. Петренко // Системні дослідження та інформаційні технології. – 2008. – № 4. – С. 97–110.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_041.pdf" mce_href="http://cad.kpi.ua/attachments/043_2008_041.pdf">Петренко А.І. Програмне GRID-забезпечення платформи gLITE / Петренко А.І. // Інформатика, обчислювальна техніка та кібернетика : Вісник Університету «Україна». – К. : Університет «Україна», 2008. – №6. – С. 23–29.</a><br mce_bogus="1"></li>
                <li>А.І. Петренко. Четвертий етап інформатизації / А.І. Петренко // Країна знань. – 2008. – № 4. – С. 18–21.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_031.pdf" mce_href="http://cad.kpi.ua/attachments/043_2008_031.pdf">Petrenko A. Educational segment of Ukranian Grid Infrastructure / Petrenko A., Velichkevich S., Alenin O. // CODATA-21, 3-8 October 2008, Kiev, Ukraine : abstracts. – Kiev, 2008. – P. 27.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_033.pdf" mce_href="http://cad.kpi.ua/attachments/043_2008_033.pdf">Petrenko A. Integrating Ukraine Into European Grid Infrastructure / Zagorodny A., Zgurovsky M., Zinovjev G., Petrenko A., Martynov E. // CODATA-21, 3-8 October 2008, Kiev, Ukraine : abstracts. – Kiev, 2008. – P. 31.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_037.pdf" mce_href="http://cad.kpi.ua/attachments/043_2008_037.pdf">Petrenko A. Educational segment of Ukranian Grid Infrastructure / Petrenko A., Velichkevich S., Alenin O. // CODATA-21, 3-8 October 2008, Kiev, Ukraine : proc. – Kiev, 2008. – P. 158–166.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_020.pdf" mce_href="http://cad.kpi.ua/attachments/043_2008_020.pdf">Петренко А.І. Застосування резонансно-тунельних діодів та резонансно-тунельних транзисторів в схемних рішеннях / Петренко А.І., Свірін П.В. / Системний аналіз та інформаційні технології : 10-а міжнародна науково-технічна конференція «САІТ-2008», 20-24 травня 2008, Київ, Україна : матеріали. – К. : НТУУ «КПІ», 2008. – С. 315–316.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_007.pdf" mce_href="http://cad.kpi.ua/attachments/043_2008_007.pdf">Петренко А.І. Grid технології в обробці даних / Петренко А.І. / Системний аналіз та інформаційні технології : 10-а міжнародна науково-технічна конференція «САІТ-2008», 20-24 травня 2008, Київ, Україна : матеріали. – К. : НТУУ «КПІ», 2008. – С. 31–32.</a><br mce_bogus="1"></li>
                <li>Петренко А.І. Вступ до Grid технологій в науці і освіті / Петренко А.І. – К. : Вид-во «Політехніка», 2008. – 122 с.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_003.pdf" mce_href="http://cad.kpi.ua/attachments/043_2008_003.pdf">А.І. Петренко. Національна Grid-інфраструктура для забезпечення наукових досліджень і освіти / А.І. Петренко // Системні дослідження та інформаційні технології. – 2008. – № 1. – С. 79–92.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2007_011.pdf" mce_href="http://cad.kpi.ua/attachments/043_2007_011.pdf">Петренко А.І. Логічні схеми на одноелектронних транзисторах / Петренко А.І., Свірін П.В. // Системні дослідження та інформаційні технології. – 2007. – № 4. – С. 7–14.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2007_012.pdf" mce_href="http://cad.kpi.ua/attachments/043_2007_012.pdf">Петренко А.І. Grid технології в науці і освіті / Петренко А.І. // Системний аналіз та інформаційні технології : 9-а міжнародна науково-технічна конф. «САІТ–2007», 15-19 травня 2007 р., Київ : матеріали конф. – К. : НТУУ «КПІ», 2007. – С. 22–23.</a><br mce_bogus="1"></li>
                <li>Петренко А.И. Метод базиса Гробнера для решения систем нелинейных уравнений / Петренко А.И., Маринич А.А. // Электроника и связь : тематический выпуск « Проблемы электроники». – 2007. – Ч. 1. – С. 117–119.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2007_022.pdf" mce_href="http://cad.kpi.ua/attachments/043_2007_022.pdf">Petrenko A.I. Development of a Grid-infrastructure for the educational and research segment of the information society in Ukraine with a focus on ecological monitoring and telemedicine / Petrenko A.I. // Data Science Journal. ¬– 2007. – Vol. 6. – P. 234–240.</a><br mce_bogus="1"></li>
                <li>Petrenko A. Development of Grid-infrastructure for educational and research segment of information society in Ukraine, with focus on ecological monitoring and telemedicine / Petrenko A. // 20-th Conference «CODATA», 2006, Beijing, China : proc. – Beijing, 2006. – P. 145–147.</li>
                <li>Zgurovsky M. National Ukrainian Grid infrastructure(UGRID) for science and education / Zgurovsky M., Petrenko A. // Computer Science and Information Technologies : Intern. Conference, October 2006, Lviv, Ukraine : proc, – Lviv, 2006. – P. 6–12.</li>
                <li>Петренко А. І. Шляхи підвищення творчої компоненти (креативності) в навчальному процесі / Петренко А. І. // Электроника и связь : тематический выпуск «Проблемы електроники». – 2006. – Ч. 2. – С. 112–116.</li>
                <li>Фельдман Л.П. Чисельні методи в інформатиці : підручник / Фельдман Л.П., Петренко А.І., Дмитрієва О.А. – К. : Видавнича група BHV, 2006. – 480 c. – (Інформатика). – ISBN 978-966-552-155-6.</li>
                <li>Petrenko A. OPTIMAL ELECTRONIC CIRCUITS and MICROSYSTEMS DESIGNER. / Petrenko A. // IEEE EAST-WEST DESIGN &amp; TEST WORKSHOP : International conf. «EWDTW’06», 15-19 September 2006, Sochi, Russia: proc. – Sochi, 2006. <span> </span><a target="_blank" href="http://cad.kpi.ua/attachments/043_2006_022.ppt" mce_href="http://cad.kpi.ua/attachments/043_2006_022.ppt">Тези</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2006_019.pdf" mce_href="http://cad.kpi.ua/attachments/043_2006_019.pdf">Petrenko A. I. Ways of creative components improvement in the engineering education / Petrenko A. I. // Modern Problems of Radio Engineering, Telecommunications, and Computer Science: International Conference TCSET’06, 28 February – 4 March 2006, Lviv-Slavsko, Ukraine: proc. – Lviv, 2006. – P. 707–710.</a><br mce_bogus="1"></li>
                <li>Петренко А.І. Чисельні методи в інформатиці : конспект лекцій / Петренко А.І.. – К. : Видавництво «Аверс», 2006. – 204 с.</li>
                <li>Петренко А.І. Конспект лекцій до курсу «Моделювання складних об’єктів та систем» : для студентів напрямку «Комп’ютерні науки». Спеціальність 7.080402 – «Інформаційні технології проектування» / Петренко А.І. – К. : Видавництво «Аверс», 2006. – 205 с.</li>
                <li>Petrenko A.I. RLC – circuits models size reduction / Petrenko A.I. // The Experience of Designing and Application of CAD Systems in Microelectronics : 8-th Intern. Conference «CADSM’05», Lviv-Polyana, 2005. – Lviv-Polyana, 2005. – P. 1–4.</li>
                <li>Петренко А.І. Архітектура мереженого комплексу схемотехнічного проектування ALLTED / Петренко А.І., Ладогубець В.В., Воєвода О.О. // Комп’ютерні системи проектування. Теорія і практика : вісник НУ «Львівська політехніка». – 2005. – № 522. – С. 30–33.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2005_007.pdf" mce_href="http://cad.kpi.ua/attachments/043_2005_007.pdf">Петренко А.І. Моделювання резонансно-тунельного діоду / Петренко А.І., Свірін П.В. // Электроника и связь : тематический выпуск «Проблемы электроники». – 2005. – Ч. 2. – С. 116–119.</a><br mce_bogus="1"></li>
                <li>Петренко A.I. Європейський досвід дослідження і розробки новітніх навчальних технологій для інформаційного суспільства / Петренко A.I. // Київський політехнік. – вересень, 2004.</li>
                <li>Петренко А.І. Розподілена САПР з використанням технологій Grid сервісів / Петренко А.І., Велічкевич С.В. // Наукові вісті НТУУ «КПІ». – 2004. – № 3. – С. 30–37.</li>
                <li>Петренко А.И. Алгоритм сокращения размерности моделей RLC-схем / Петренко А.И., Петренко И.А. // Электроника и связь. – 2004. – № 23. – С. 49–56.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2003_010.pdf" mce_href="http://cad.kpi.ua/attachments/043_2003_010.pdf">Petrenko A. Teleworking in Computer – Aided Circuit Design / Petrenko A. // The Experience of Designing and Application of CAD Systems in Microelectronics : 7-th Intern. Conference «CADSM’03», 18-21 February 2003, Lviv-Slavsko, Ukraine: proc. – Lviv, 2003. – P. 25–29.</a><br mce_bogus="1"></li>
                <li>Petrenko A. Teleworking in Computer – Aided Circuit Design / Petrenko A. // Circuit Theory and Design : European Conference «ECCTD’03», Kracow, Poland, 1-4 Sept. 2003 : proc. – Krakow, 2003. – P. 215.</li>
                <li>Кирюша Б.А. Модели СВЧ полевых GaAs транзисторов для САПР / Кирюша Б.А., Петренко А.И. // Электроника и связь. – 2003. - № 19. – С. 128-139.</li>
                <li>Петренко А.І. Програма порівняльного дослідження метода пошуку кривої розв’язку / Петренко А.І., Калюжний О.О., Сорокін Ю.В. // Электроника и связь. – 2003. – № 18. – С. 3–5.</li>
                <li>Петренко А.И. Распределенная интегрированная вычислительная среда Grid / Петренко А.И., Величкевич С.В. // Электроника и связь. – 2003. – № 19. – С. 36–42.</li>
                <li>Петренко А.І. Європейський досвід дослідження і розробки новітніх навчальних технологій для інформаційного суспільства / Петренко А.І. // Вісті ВМУРОЛ «Україна». – 2002. – № 3.</li>
                <li>Петренко A. Інформаційні технології в освіті (віртуальні університети і лабораторії) / Петренко A. // Вісті ВМУРОЛ «Україна». – 2002. – № 1.</li>
                <li>Петренко А.І. ОСНОВИ АВТОМАТИЗОВАНОГО ПРОЕКТУВАННЯ ОБ"ЄКТІВ ТА СИСТЕМ (Конспект лекцій) / Петренко А.І. – К. : Видавництво ВМУРОЛ «Україна», 2002. – 211 с.</li>
                <li>Петренко А.І. Mережеві засоби навчання і співробітництва у інформаційному суспільстві / Петренко А.І. // Інформаційні технології в дослідженнях, промисловасті і навчанні : Міжнародна конференція, Лютий 2002, Львів. – Львів, 2002.</li>
                <li>Петренко А.І. ОБЧИСЛЮВАЛЬНА МАТЕМАТИКА (Конспект лекцій) / Петренко А.І. – К. : Видавництво ВМУРОЛ «Україна», 2002. – 212 с.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2002_2.pdf" mce_href="http://cad.kpi.ua/attachments/043_2002_2.pdf">Кирюша Б.А. Обзор моделей гетеротранзисторов для СВЧ диапазона / Кирюша Б.А., Петренко А.И. // Электроника и связь. – 2002. – № 16. – С. 3–15.</a><br mce_bogus="1"></li>
                <li>Кирюша Б. Модели гетеротранзисторов для больших сигналов для САПР СВЧ устройств / Кирюша Б.,Петренко А.І. // Электроника и связь. – 2002.</li>
                <li>Петренко А.І. Принципи побудови мереженого комплексу схемотехнічного проектування ALLTED / Петренко А.І., Ладогубець В.В., Воєвода О.О. // Электроника и связь. – 2002. – № 17. – С. 56–58.</li>
                <li>Петренко А. Инструментальная поддержка дистанционного обучения. / Петренко А., Киселев Г. // Розвиток інформаційного суспільства в Україні : Другий Міжнародний конгрес, 4-6 грудня 2001 р., Київ, НТУУ "КПІ". – Киев, 2001.</li>
                <li>Петренко A. Інформаційні технології в освіті (віртуальні Університети і лабораторії) / Петренко A. // Вища освіта. – 2001. – № 3.</li>
                <li>Petrenko A. Teleworking in computer - aided design / Petrenko A. // Teleworking in Research, Medicine and Business : Intern. Conference, NTUU "KPI", 19-20 April 2001, Kiev : abstracts. – Kiev, 2001. – P. 20.</li>
                <li>Petrenko A. Web-based CAD for distributed design / Petrenko A. // Experience of Designing and Application of CAD Systems in Microelectronics : 6-th International Conference «CADSM’2001», Lviv-Slavsko, 12-17 February 2001, Ukraine: proc.</li>
                <li>Петренко А.И. Проектирование СВЧ устройств с помощью ALLTED / Петренко А.И., Кирюша Б.А. // Электроника и связь. – 2001. – № 13. – С. 3–6.</li>
                <li>Петренко А. Віртуальні лабораторії для дистанційної освіти і співпраці / Петренко А. // Электроника и связь. – 2001. – № 11. – С. 3–5.</li>
                <li>Petrenko A. Networked CAD for Distributed Design (Tutorial 8) / Petrenko A. // Circuit Theory and Design : European Conference «ECCTD'01», Espoo, Finland, Augest 28-31, 2001.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2000_009.pdf" mce_href="http://cad.kpi.ua/attachments/043_2000_009.pdf">А.I. Петренко. Особливості візуалізації даних в САПР за допомогою OpenGL. / А.I. Петренко, Я.I. Корначевський // Электроника и связь. – 2000. – Т. 2, № 8. – С. 279–282.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2000_007.pdf" mce_href="http://cad.kpi.ua/attachments/043_2000_007.pdf">А.И. Петренко. САПР интегральных схем на платформе ПК / А.И. Петренко, С.А. Цветкова // Электроника и связь. – 2000. – Т. 1, № 8. – С. 149–151.</a><br mce_bogus="1"></li>
                <li>Petrenko A.I. BASICS OF ELECTRONIC CIRCUITS COMPUTER - AIDED DESIGN : Material of seminars / Petrenko A.I. – Pohang University of Science and Technology, 2000. – 240 p.</li>
                <li>Петренко А. Інформаційні технології глобалізації інженерних інновацій / Петренко А. //. Інформаційне суспільство в Україні - стан, проблеми, перспективи : конгрес, НТУУ "КПІ", вересень 2000, Київ : матеріали. – Київ, 2000. – С. 231–234.</li>
                <li>Петренко А.И. Формирование графического представления соединений схемы замещения в схемных редакторах / Петренко А.И., Ладогубец В.В., Марченко Е.В. // Электроника и связь. – 2000. – № 9. – С. 18–31.</li>
                <li>Петренко А. Розробка і дослідження мережевих систем автоматизації проектування (САПР) (Web-based Design) / Петренко А. // Электроника и связь. – 2000. – № 9. – С. 3–5.</li>
                <li>Петренко А.И. Подсистема графического ввода САПР ALLTED / Петренко А.И., Ладогубец В.В., Марченко Е.В. // Электроника и связь. – 1999. – № 7. – С. 107–109.</li>
                <li>Young Yu. Windows-based CAD System for System IC Designs / Young Yu, Anatoly Petrenko // Mixed Design of Integrated Circuits and Systems : Intern. Conference «MIXDES'99», 17-19 June 1999, Krakov, Poland : proc. – 1999. – P. 539–541.</li>
                <li>Petrenko A.I. Optimal Circuit Designer / Petrenko A.I. // Circuit Theory and Design : European Conference «ECCTD'99» : Proc. – 1999.</li>
                <li>ALL TECHNOLOGY DESIGNER: Reference Book / под ред. А.И. Петренко, Юнг Су Ю. – SunMoon University, 1999. – 342 p.</li>
                <li>Петренко А.И. Корейско-украинский семинар по проектированию СБИС / Петренко А.И. // ComputerWorld. – 24.02.1999. – №6 (221). – C. 15.</li>
                <li>Петренко А.І. Система MyCAD для проектування замовних ВІС, орієнтована на персональні комп'ютери / Петренко А.І. // Досвід розробки і застосування САПР в мікроелектроніці : Міжнародна конференція «CADSM’99», 1-6 лютого 1999, Львів : праці. – 1999. – С..2–3.</li>
                <li>Петренко А.И. Кафедра систем автоматизированого проектирования / Петренко А.И. // Комп'ютер класс. – 1999. – № 3–4. – С. 18–19.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_007.pdf" mce_href="http://cad.kpi.ua/attachments/043_1998_007.pdf">Нгуен Х.Ч. Алгоритм временного моделирования при экспресс-анализе цепей на МОП-транзисторах / Нгуен Х.Ч., Ладогубец В.В., Петренко А.И. // Радиоэлектроника. – 1998. – № 3. – С. 40–48. – (Известия вузов).</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_003.pdf" mce_href="http://cad.kpi.ua/attachments/043_1998_003.pdf">Петренко А.И. COMNET III: программа автоматизации проектирования компьютерных сетей / Петренко А.И., Мартыненко В.И. // Электроника и связь. – 1998. – № 5. – С. 105–110.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_012.pdf" mce_href="http://cad.kpi.ua/attachments/043_1998_012.pdf">Петренко А.И. Міжнародне співробітництво по навчанню проектуванню електричних схем і систем через мережу INTERNET / Петренко А.І. // Электроника и связь. – 1998. – Ч. 3. – № 4. – С. 555–556.</a><br mce_bogus="1"></li>
                <li>Petrenko A.I. Network-oriented Electronic Design under COPERNICUS-INCO Program / Petrenko A.I. // Engineering Education : 6-th World Conference, Cracow, September,1998 : proc. – Cracow, 1998.</li>
                <li>Петренко А.І. Iнформацiйнi технологii в освiтi (вiдкрите дистанцiйне павчання) / Петренко А.І. // Сучаснi проблеми САПР та пiдготовки кадрiв : Львiв,1998 : праці. – Львов, 1998.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_002.pdf" mce_href="http://cad.kpi.ua/attachments/043_1998_002.pdf">Петренко А.І. Комп'ютерне проектування в інфор-маційному середовищі Internet / Петренко А.І. // Наукові вісті НТУУ "КПІ". – 1998. – № 2. – С. 11–21.</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_001.pdf" mce_href="http://cad.kpi.ua/attachments/043_1998_001.pdf">Petrenko A.I. Developing Educational and User Applications of Network-oriented Electronic Design within COPERNICUS Telematics Programm / Petrenko A.I. // The Intern. Jounal of Engineering of Education. – 1998. – Vol. 14, № 6. – P. 442–448. – (TEMPUS Publications).</a><br mce_bogus="1"></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_1998_008.pdf" mce_href="http://cad.kpi.ua/attachments/043_1998_008.pdf">Нгуен Х.Ч. Концепция релаксации и временной анализ интегрированных МОП-цепей / Нгуен Х.Ч., Ладогубец В.В., Петренко А.И. // Радиоэлектроника. – 1998. – № 8. – С. 60–67. – (Известия вузов).</a><br mce_bogus="1"></li>
                <li>Петренко А.И. Новые информационные технологии: сетевая поддержка рабочих мест (Teleworking) / Петренко А.И. // Электроника и связь. – 1996. – № 1. – С. 5–9.</li>
            </ol>

        </div>
    </div>

    <?php get_footer(); ?>
</body>

</html>