<?php /* Template Name: FinogenovPublications */

?>

<?php
/**
 * @package start_theme
 * 
 */

get_header(); ?>
<html>

<head>

</head>

<body>


    <div class="wrapper">
        <div class="bannerScience">
            <div class="column">
                <div class="text-banner">
                    <p><br></p>
                    <p><b>Не знаєш де опублікувати свою роботу?</b></p>
                    <p>Слідкуй за рубрикою <a href="#">Конференції</a>. Завжди корисна інформація, ключові дати та активні контакти!</p>
                    <p><br></p>
                </div>
            </div>
        </div>
        <div class="text-page">
            <h1>Публікації: Фіногенов О.Д.</h1>
            <br>

            <ol>
                <li>Попович Е.С. Особенности определения индекса случайной согласованности в метода анализа иерархий (МАИ) / Финогенов А.Д., Литвиненко П.Л., Попович Е.С. // "Прикладна геометрія, дизайн та об'єкти інтелектуальної власності" : 3-а міжнародна науково-практична конференція студентів, аспірантів та молодих вчених, 22-23 квітня 2014, Київ : матеріали. - К., 2014. - С. 205-210.</li>
                <li>Теорія прийняття рішень : Методичні вказівки до виконання лабораторних робіт для студентів напряму підготовки 6.050101 «Комп’ютерні науки», спеціальностей 8.05010102 «Інформаційні технології проектування» та 8.05010103 «Системне проектування» денної та заочної форм навчання / Укладачі : О.Ю. Безносик, В.В. Ладогубець, О.Д. Фіногенов. – К. : НТУУ «КПІ», 2013 р. – 76 c.</li>
                <li>Фіногенов О. Оцінка ефективності вибору порядку методу в алгоритмі чисельного інтегрування на основі різниць вищих порядків / Фіногенов О.Д. // Вісник НУ «Львівська політехніка»: Комп’ютерні науки та інформаційні технології. – 2013. – № 751. – С. 351–355.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2013_016.pdf" mce_href="/attachments/043_2013_016.pdf">Zgurovsky M. WebALLTED: Interdisciplinary Modeling in Grid and Cloud / Zgurovsky Michael, Anatolii Petrenko, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh // Computer Science. – Krakow : AGH, 2013. – № 14 (2). – P. 295–306.</a></li>
                <li>Petrenko A. Simulation in GridALLTED Complex / Anatolii Petrenko, Mykhailo Lobur, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh, Tetyana Ladogubets // The Experience of Designing and Application of CAD Systems in Microelectronics : 12-th Intern. Conf. «CADSM’2013», 19-23 February 2013, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv, 2013. – P. 422–424. – ISBN 978-617-607-393-2.</li>
                <li>Інформаційні системи прийняття рішень і логічних висновків : Методичні вказівки до виконання комплексної контрольної роботи для студентів напряму підготовки 6.050101 «Комп’ютерні науки», спеціальності 8.05010103 «Системне проектування» денної та заочної форм навчання / Укладачі : О.Ю. Безносик, В.В. Ладогубець, О.Д. Фіногенов. – К. : НТУУ «КПІ», 2013 р. – 33 c.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_050.pdf" mce_href="/attachments/043_2012_050.pdf">Булах Б.В. Модификация способа учета баланса загрузки при выполнении параллельных программ на вычислительном кластере / Булах Б.В., Чекалюк В.В., Ладогубец В.В., Финогенов А.Д. // Інформатика, управління та обчислювальна техніка : вісник НТУУ «КПІ». – 2012. – Вип. 57. – С. 56–59.</a></li>
                <li>Теорія прийняття рішень : Методичні вказівки до виконання комплексної контрольної роботи для студентів спеціальностей 8.05010102 «Інформаційні технології проектування» та 8.05010103 «Системне проектування» денної та заочної форм навчання / Укладачі : О.Ю. Безносик, В.В. Ладогубець, О.Д. Фіногенов. – К. : НТУУ «КПІ», 2012 р. – 42 c.</li>
                <li>Методи багатокритеріальної та мінімаксної оптимізації : Методичні вказівки до виконання лабораторних робіт для студентів спеціальностей 8.05010102 «Інформаційні технології проектування» та 8.05010103 «Системне проектування» денної та заочної форм навчання / Укладачі : В.В. Ладогубець, О.Д. Фіногенов. – К. : НТУУ «КПІ», 2012 р. – 109 c.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_044.pdf" mce_href="/attachments/043_2012_044.pdf">Финогенов А.Д. Графические редакторы для схемотехнического проектирования / Ляпин П.С., Мельничук Р.Н., Финогенов А.Д. // Інформатика, управління та обчислювальна техніка : вісник НТУУ «КПІ». – 2012. – Вип. 55. – С. 187–193.</a></li>
                <li>Zgurovsky M. WebALLTED: Interdisciplinary Simulation in Grid / Michael Zgurovsky, Anatoly Petrenko, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh // Cracow Grid Workshop : 12-th Cracow Grid Workshop «CGW’12», 22-24 October 2012, Krakow, Poland : proc. – Krakow, 2012. – P. 61–62. – ISBN 978-83-61433-06-4.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_040.pdf" mce_href="/attachments/043_2012_040.pdf">Zgurovsky M. WebALLTED: Interdisciplinary Simulator Based on Grid Services / Zgurovsky M., Petrenko A., Ladogubets V., Finogenov O., Bulakh B. // East-West Design &amp; Test Symposium : 10-th IEEE East-West Design &amp; Test Symposium «EWDTS’2012», 14-17 September 2012, Kharkov, Ukraine: proc. – Kharkov, 2012. – P. 126–129.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_018.pdf" mce_href="/attachments/043_2012_018.pdf">Финогенов А.Д. Анализ электронных платежных систем Украины / Финогенов А.Д., Кожома Е.И. // Системный анализ и информационные технологии: 14-я международная научно-техническая конференция «САИТ-2012», 24 апреля 2012, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2012. – С. 300–301.</a></li>
                <li>Petrenko A. Service-Oriented Architecture for Grid-Enabled Computer Simulation Software / Anatolii Petrenko, Volodymyr Ladogubets, Oleksii Finogenov, Bogdan Bulakh // Perspective Technologies and Methods in MEMS Design : 8-th International Conference MEMSTECH’2012, 18-21 April 2012, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2012. – P. 179–181.</li>
                <li>Ladogubets V. An Approach to the Size Reduction for Very Large Circuit Equivalents of MEMS Non-Electrical Parts Mathematical Model / Volodymyr Ladogubets, Oleksii Finogenov, Oleksandr Beznosyk, Oleksandr Popov, Michal Szermer, Wojciech Zabierowski, Piotr Zajac // Perspective Technologies and Methods in MEMS Design : 8-th International Conference MEMSTECH’2012, 18-21 April 2012, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2012. – P. 174–177.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2012_003.pdf" mce_href="/attachments/043_2012_003.pdf">Ladogubets V.V. Forming a User Function Dynamic Library for ALLTED CAD Software / Ladogubets V.V., Finogenov O.D., Beznosyk O. Yu. // Electronics and Nanotechnology : 32-th International Scientific Conference «ELNANO’2012», 10-12 April 2012, Kiev, Ukraine : proc. – Kiev, 2012. – P. &nbsp;123.</a></li>
                <li>Ладогубец В.В. Объединение пакета NetALLTED со сторонними пакетами САПР / Ладогубец В.В., Финогенов А.Д., Старовойтенко Д.С. // Комп’ютерні технології: наука і освіта : 4-а Всеукраїнська науково-практична конференція : тези доповідей. ­– К. : Університиет «Україна», 2012. – С. 59–62.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_045.pdf" mce_href="/attachments/043_2011_045.pdf">Методичні вказівки до виконання лабораторних робіт з дисципліни «Методи оптимізації» для студентів напряму підготовки 6.050101 «Комп'ютерні науки», спеціальностей 8.05010102 «Інформаційні технології проектування» та&nbsp; 8.05010103 «Системне проектування» денної та заочної форм навчання / Укл. В.В.Бобін, В.В.Ладогубець, О.Д.Фіногенов. – Львів : ПП «Вежа і Ко», 2011 р. – 128 c. – ISBN 978-617-607-230-0.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_035.pdf" mce_href="/attachments/043_2011_035.pdf">Петренко А.І. Дослідження архітектури комплексу схемотехнічного моделювання GridALLTED / Петренко А.І., Ладогубець В.В., Фіногенов О.Д., Булах Б.В. // Вісник університету «Україна» : Інформатика, обчислювальна техніка та кібернетика. – К. : Університет «Україна», 2011. – № 2. – С. 65–70.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_034.pdf" mce_href="/attachments/043_2011_034.pdf">Ладогубец В.В. Методы выбора размера шага для параллельного алгоритма динамического анализа / Ладогубец В.В., Крамар. А.В., Финогенов А.Д. // Вісник університету «Україна» : Інформатика, обчислювальна техніка та кібернетика. – К. : Університет «Україна», 2011. – № 2. – С. 12–17.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_029.pdf" mce_href="/attachments/043_2011_029.pdf">Ладогубец В.В. Анализ методов управления вычислениями при моделировании сложных объектов // Ладогубец В.В., Финогенов А.Д., Безносик А.Ю. // Математические методы в технике и технологиях : 24-я международная конференция «ММТТ-24» : 2011, Саратов, Россия : сб. тр. в 10-ти томах. – К. : Национальный техн. ун-т. Украины «КПИ», 2011. – Т. 1. – С. 142–144.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_022.pdf" mce_href="/attachments/043_2011_022.pdf">Фіногенов О.Д. Оцінка точності скорочення лінійних схем при використанні матричного алгоритму / Фіногенов О.Д., Кот Д.М., Попов О.О. // Системный анализ и информационные технологии : 13-я международная научно-техническая конференция «САИТ-2011», 23-28 мая 2011, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2011. – С. 393.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_002.pdf" mce_href="/attachments/043_2011_002.pdf">Ladogubets V. Features of the Optimization of Mechanical Component Macromodels / Vladimir Ladogubets, Oleksii Finogenov, Oleksandr Beznosyk, Tatiana Ladogubets // The Experience of Designing and Application of CAD Systems in Microelectronics : 11-th Anniversary Intern. Conf. «CADSM’2011», 23-25 February 2011, Lviv-Polyana (Zakarpattya), Ukraine : proc. – Lviv, 2011. – P. 410–412.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_003.pdf" mce_href="/attachments/043_2011_003.pdf">Ладогубець В.В. Методи підвищення ефективності Y–Δ перетворення при побудові схемних макромоделей МЕМС / Ладогубець В.В., Фіногенов О.Д., Безносик О.Ю. // Электроника и связь : тематический выпуск «Электроника и нанотехнологии». – 2011. – № 1. – С. 82–87.</a><span><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_003abs.pdf" mce_href="/attachments/043_2011_003abs.pdf">&nbsp; Тези</a></span></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2011_007.pdf" mce_href="/attachments/043_2011_007.pdf">Ladogubets V. Choosing an Objective Function Type When Adjusting Mechanical Components’ Macromodel Parameters / Oleksandr Beznosyk, Oleksii Finogenov, Volodymyr Ladogubets // Perspective Technologies and Methods in MEMS Design : 7-th International Conference MEMSTECH’2011, 11-14 May 2011, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv : Publishing House Vezha&amp;Co, 2011. – P. 239–240.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_038.pdf" mce_href="/attachments/043_2010_038.pdf">Ladogubets V. Straight Pipeline Simulation / Ladogubets V., Tchkalov O., Beznosyk O., Finogenov O. // CAD in Machinery Design. Implementation and Educational Problems : 18-th Ukranian–Polish Conference «CADMD’2010», October 14-16, 2010, Lviv, Ukraine: Proc. – Lviv: Vezha &amp; Co , 2010. – P. 23–26.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_043.pdf" mce_href="/attachments/043_2010_043.pdf">Ладогубец В.В. Методы выбора размера шага для параллельного алгоритма динамического анализа / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Комп’ютерні технології: наука і освіта : 5-а Всеукраїнська науково-практична конференція : тези доп. – Київ, 2010. – С. 134–138.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_051.pdf" mce_href="/attachments/043_2010_051.pdf">Ладогубець В.В. Підвищення надійності методів керування обчисленнями / Ладогубець В.В., Крамар О.В., Фіногенов О.Д. // Інформатика, обчислювальна техніка та кібернетика : Вісник Університету «Україна». – К. : Університет «Україна», 2010. – №8. – С. 96–100.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_056.pdf" mce_href="/attachments/043_2010_056.pdf">Ладогубець В.В. Особливості оптимізації макромоделей механічних компонентів / Ладогубець В.В., Фіногенов О.Д., Безносик О.Ю. // Інформатика, управління та обчислювальна техніка : вісник НТУУ «КПІ». – 2010. – Вип. 52. – С. 96–102.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_001.pdf" mce_href="/attachments/043_2010_001.pdf">Oleksandr Beznosyk. Presentation of a System of Ordinary Differential Equations as an Equivalent Electrical Circuit / Oleksandr Beznosyk, Oleksii Finogenov, Volodymyr Ladogubets // Perspective Technologies and Methods in MEMS Design : VI-th International Conference MEMSTECH’2010, 20-23 April 2010, Lviv-Polyana, Ukraine: proc. – Lviv : Publishing House Vezha &amp; Co , 2010. – P. 116–120.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_003.pdf" mce_href="/attachments/043_2010_003.pdf">Ладогубец В.В. Использование мультипроцессорных вычислительных систем средствами схемотехнического проектирования / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Электроника и связь : тематический выпуск «Электроника и нанотехнологии». – 2010. – № 5. – С. 232–235.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2010_019.pdf" mce_href="/attachments/043_2010_019.pdf">Ладогубец В.В. Методы управления динамическим анализом сложных объектов / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Системный анализ и информационные технологии : 12-я международная научно-техническая конференция «САИТ-2010», 25-29 мая 2010, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2010. – С. 373.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_032.pdf" mce_href="/attachments/043_2009_032.pdf">Ладогубец В.В. Расчет времени выполнения параллельного метода численного интегрирования на основе разностей высших порядков / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Вісник НТУУ «КПІ». Інформатика, управління та обчислювальна техніка: Зб. наук. пр. – К. : ВЕК+, 2009. – № 50. – С. 23–29.</a></li>
                <li>Петренко А.И. Расчет собственных частот мембранных структур с использованием пакетов схемотехнического проектирования / Петренко А.И., Ладогубец В.В., Финогенов А.Д. [и др.] // Радиоэлектроника. – 2009. – № 7. – С. 19–25. – (Известия вузов).</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_020.pdf" mce_href="/attachments/043_2009_020.pdf">Петренко А.І. Використання пакетів схемотехнічного проектування для побудови моделей механічних компонентів / Петренко А.І., Ладогубець В.В., Фіногенов О.Д. [та ін.] // Вісник НУ «Львівська політехніка»: Комп’ютерні науки та інформаційні технології. – 2009. – № 638. – С. 18-22.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_018.pdf" mce_href="/attachments/043_2009_018.pdf">Безносик О.Ю. Метод отримання схемних аналогів макромоделей МЕМС / Безносик О.Ю., Фіногенов О.Д., Ладогубець Т.С., Ладогубець О.В. // Прикладна математика та комп'ютинг : 1-а наукова конференція магістратів та аспірантів «ПМК-2009», 15-17 квітня 2009, Київ, Україна : зб. тез / ред. кол. : С.В. Сирота (гол. ред.) та ін. – К. : НТУУ "КПІ", 2009. – С. 116–119.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_013.pdf" mce_href="/attachments/043_2009_013.pdf">Ладогубец В.В. Анализ эффективности выбора порядка в неявном методе численного интегрирования на основе разностей высших порядков / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Системный анализ и информационные технологии : 11-я международная научно-техническая конференция «САИТ-2009», 26-30 мая 2009, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2009. – С. 436.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_008.pdf" mce_href="/attachments/043_2009_008.pdf">Безносик А.Ю. Использование пакетов схемотехнического проектирования для расчета деформаций механических компонентов / Безносик А.Ю., Ладогубец В.В., Финогенов А.Д.,&nbsp; Чкалов А.В. // Системный анализ и информационные технологии : 11-я международная научно-техническая конференция «САИТ-2009», 26-30 мая 2009, Киев, Украина : материалы. – К. : УНК "ИПСА" НТУУ "КПИ", 2009. – С. 419.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_006.pdf" mce_href="/attachments/043_2009_006.pdf">Oleksandr Beznosyk. Making a Mechanical Components Library for Circuit Design Software / Oleksandr Beznosyk, Oleksii Finogenov, Volodymyr Ladogubets, Oleksii Tchkalov // Perspective Technologies and Methods in MEMS Design : V-th International Conference MEMSTECH’2009, 22-24 April 2009, Lviv-Polyana, Ukraine: proc. – Lviv : Publishing House Vezha &amp; Co , 2009. – P. 120-122.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_005.pdf" mce_href="/attachments/043_2009_005.pdf">Anatolii Petrenko. Using Optimization Procedures to Calculate Parameters of MEMS Macromodels / Anatolii Petrenko, Volodymyr Ladogubets, Oleksandr Beznosyk, Oleksii Finogenov // The Experience of Designing and Application of CAD Systems in Microelectronics : 10-th Anniversary Intern. Conf. «CADSM’2009», 24-28 February 2009, Polyana-Svalyava (Zakarpattya), Ukraine : proc. – Lviv, 2009. – P. 511–514.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2009_002.pdf" mce_href="/attachments/043_2009_002.pdf">Ладогубец В.В. Методика построения моделей механических компонентов МЭМС для пакетов схемотехнического проектирования / Ладогубец В.В., Чкалов А.В., Безносик А.Ю., Финогенов А.Д. // Электроника и связь : тематический выпуск «Электроника и нанотехнологии». – 2009. – Ч. 1, № 2/3. – С. 298–305.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_002.pdf" mce_href="/attachments/043_2008_002.pdf">Фіногенов О.Д. Паралельний метод чисельного інтегрування жорстких систем диференційних рівнянь з визначенням кращого порядку на кроці / Фіногенов О.Д. // Комп'ютері технології друкарства. – 2008. – № 20. – С. 108–113.</a></li>
                <li>Ладогубец В.В. Адаптация параллельного алгоритма СПУИП для кластера НТУУ «КПИ» / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Вісник НТУУ «КПІ». Інформатика, управління та обчислювальна техніка: Зб. наук. пр. – 2008. – № 48. – С. 99–103.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_025.pdf" mce_href="/attachments/043_2008_025.pdf">Ладогубец В.В. Метод построения макромоделей МЭМС / Ладогубец В.В., Чкалов&nbsp;А.В., Безносик А.Ю.,&nbsp; Финогенов А.Д. // СВЧ-техника и телекоммуникационные технологии : 18-я Международная Крымская конференция «КрыМиКо’2008», 8-12 сент. 2008, Севастополь, Крым, Украина : материалы. – Севастополь: Вебер, 2008. – Т. 1. – С. 147–148.</a></li>
                <li>Ладогубец В.В. Метод формирования схемных реализаций математических моделей неэлектрических объектов / Ладогубец В.В., Чкалов&nbsp;А.В., Безносик А.Ю.,&nbsp; Финогенов А.Д. // Моделювання та інформаційні технології : зб. наук. пр. – 2008. – Вип. 46. – С.&nbsp;114–120.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_023.pdf" mce_href="/attachments/043_2008_023.pdf">Beznosyk O. Using circuit design software to simulate microelectromechanical components / Beznosyk O., Finogenov O., Ladogubets V., Tchkalov O. // Perspective Technologies and Methods in MEMS Design : IV-th International Conference of Young Scientists MEMSTECH’2008, 21-24 May 2008, Lviv-Polyana, Ukraine: proc. – Lviv : Publishing House Vezha &amp; Co , 2008. – P. 130–133.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_012.pdf" mce_href="/attachments/043_2008_012.pdf">Безносик О.Ю.&nbsp;Використання пакетів схемотехнічного проектування для моделювання механічних компонентів / Безносик О.Ю., Ладогубець В.В., Фіногенов О.Д., Чкалов&nbsp;О.В. // Системний аналіз та інформаційні технології : 10-а міжнародна науково-технічна конференція «САІТ-2008», Київ : матеріали. – К. : НТУУ «КПІ», 2008. – С. 286.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_011.pdf" mce_href="/attachments/043_2008_011.pdf">Безносик А.Ю. Построение пассивных моделей МЭМС / Безносик А.Ю., Ладогубец В.В., Финогенов А.Д., Чкалов&nbsp;А.В. // Системный анализ и информационные технологии : 10-я международная научно-техническая конференция «САИТ-2008», 20-24 мая 2008, Киев, Украина : материалы. – К.: НТУУ «КПИ», 2008. – С. 285.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2008_001.pdf" mce_href="/attachments/043_2008_001.pdf">Ладогубец В.В. Методы макромоделирования МЭМС / Ладогубец В.В., Безносик А.Ю., Крамар А.В., Финогенов А.Д. // Электроника и связь : тематический выпуск «Проблемы электроники». – 2008. – Ч. 1. – С. 244–248.</a></li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2007_009.pdf" mce_href="/attachments/043_2007_009.pdf">Ладогубец В.В. Параллельный алгоритм численного интегрирования, основывающийся на разностях высших порядков с варьируемым шагом и порядком метода / Ладогубец В.В., Крамар А.В., Финогенов А.Д. // Системный анализ и информационные технологии : 9-я международная научно-техническая конференция «САИТ-2007», Киев : материалы.. – К.: НТУУ «КПИ», 2007. – С. 156.</a></li>
                <li>Финогенов А.Д. Особенности увеличения шага в неявных методах численного интегрирования систем дифференциальных уравнений / Финогенов А.Д. // Электроника и связь.&nbsp;– 2007. – № 38. – С. 82–87.</li>
                <li>Ладогубец В.В. Параллельный алгоритм численного интегрирования математических моделей сложных систем&nbsp;/ Ладогубец В.В., Финогенов А.Д. // Электроника и связь : тематический выпуск «Проблемы электроники». – 2007. – Ч. 1. – С. 101–104.</li>
                <li><a target="_blank" href="http://cad.kpi.ua/attachments/043_2005_010.pdf" mce_href="/attachments/043_2005_010.pdf">Ладогубец В.В. Пути повышения эффективности программных средств САПР / Ладогубец В.В., Финогенов А.Д.// СВЧ-техника и телекоммуникационные технологии : 15-я Международная Крымская конференция «КрыМиКо’2005», 12-16 сент. 2005, Севастополь, Крым, Украина : материалы. – Севастополь: Вебер, 2005. – Т. 2. – С. 472–473.</a></li>
                <li>Финогенов А.Д. Особенности реализации параллельных алгоритмов для однопроцессорных пакетов / Финогенов А.Д., Ладогубец В.В. // Электроника и связь. – 2005. – № 25. – С. 95–98.</li>
            </ol>

        </div>
    </div>

    <?php get_footer(); ?>
</body>

</html>